// Copyright © 2026 Kirky.X
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Internationalization (ICU i18n — Phase 8).
//!
//! Wraps `rust-i18n` to provide:
//! - Compile-time locale loading from `locales/` directory (via `i18n!` in lib.rs)
//! - Runtime locale switching via [`init_i18n`] (sets process-wide default locale)
//! - `t!()` macro for translation lookups (re-exported from `rust_i18n`)
//! - Per-request locale translation via [`translate_with_locale`] /
//!   [`translate_with_locale_args`] — used by HTTP handlers to translate
//!   error messages based on the `Accept-Language` header without mutating
//!   global locale state (Phase 8 T041).
//!
//! # Phase 8 T041 (MED-001) — Hidden API Usage
//!
//! We use `crate::_rust_i18n_try_translate` (generated by the `i18n!`
//! macro) and `rust_i18n::replace_patterns` because rust-i18n 3.x does
//! not expose a public per-locale translate API. These are
//! `#[doc(hidden)] pub fn` and may change in minor versions. We pin to
//! `rust-i18n = "3.1"` in `Cargo.toml` to limit breakage risk. If
//! rust-i18n 4.x exposes a stable API, migrate.

use smallvec::SmallVec;
use std::borrow::Cow;

/// Initialize the i18n system with the given locale.
///
/// Must be called once at startup, before any `t!()` lookup that depends
/// on a non-default locale. The locale string must match a top-level key
/// in `locales/<locale>.yml` (e.g. `"en"`, `"zh-CN"`).
///
/// # Example
/// ```ignore
/// nebulaid::core::i18n::init_i18n("en");
/// ```
pub fn init_i18n(locale: &str) {
    rust_i18n::set_locale(locale);
}

/// Translate a key under the given locale, without pattern arguments.
///
/// Looks up the key in `locales/<locale>.yml`. If the key is missing for
/// the requested locale, falls back to the crate default locale (`en`)
/// via `rust-i18n`'s fallback chain. If still missing, returns the key
/// itself.
///
/// Unlike `t!()` (which consults the global locale set by `set_locale`),
/// this function does **not** mutate or read global state and is safe
/// for concurrent use across requests with different `Accept-Language`
/// headers.
pub fn translate_with_locale(locale: &str, key: &str) -> String {
    translate_with_locale_cow(locale, key).into_owned()
}

/// Phase 8 T041 (M2 perf fix) — zero-allocation translation lookup
/// returning `Cow<'static, str>`.
///
/// When the looked-up string is `Borrowed` (the common case — `rust-i18n`
/// embeds locale strings as static data at compile time via `i18n!`),
/// this function returns `Cow::Borrowed` and avoids allocating a new
/// `String`. Callers that only need to read the translation can use
/// this directly; callers that need an owned `String` can call
/// `into_owned()` on the result.
pub fn translate_with_locale_cow(locale: &str, key: &str) -> Cow<'static, str> {
    crate::_rust_i18n_try_translate(locale, key).unwrap_or_else(|| Cow::Owned(key.to_string()))
}

/// Translate a key under the given locale, substituting `%{name}` patterns.
///
/// `args` is a slice of `(pattern_name, value)` pairs; each `%{pattern_name}`
/// in the translated string is replaced with the corresponding `value`.
/// Empty `args` skips the substitution pass for efficiency.
///
/// Like [`translate_with_locale`], this function does not touch global
/// locale state and is safe for concurrent per-request use.
///
/// Phase 8 T041 (M1 perf fix) — uses `SmallVec` for the keys/values
/// scratch buffers. Typical error responses carry 1–2 args, so the
/// `SmallVec<[_; 4]>` capacity lives on the stack and avoids the two
/// heap allocations that the previous `args.iter().cloned().unzip()`
/// implementation performed unconditionally.
pub fn translate_with_locale_args(locale: &str, key: &str, args: &[(&str, String)]) -> String {
    let translated = translate_with_locale_cow(locale, key).into_owned();
    if args.is_empty() {
        return translated;
    }
    let mut keys: SmallVec<[&str; 4]> = SmallVec::with_capacity(args.len());
    let mut values: SmallVec<[String; 4]> = SmallVec::with_capacity(args.len());
    for (k, v) in args {
        keys.push(*k);
        values.push(v.clone());
    }
    rust_i18n::replace_patterns(&translated, &keys, &values)
}

/// Phase 8 T041 (M3 perf fix) — borrow-friendly variant of
/// [`translate_with_locale_args`] accepting `Cow<str>` values.
///
/// `replace_patterns` requires `&[String]` for values, so a `String`
/// allocation per *owned* value is unavoidable. However, when the
/// caller passes `Cow::Borrowed(&str)` (the common case — borrowing
/// from a long-lived `String` field on the error variant), no
/// allocation is performed. The keys slice is `&[&str]` and lives
/// entirely on the stack via `SmallVec`.
///
/// This variant is used by `CoreError::to_localized_string` to avoid
/// the per-call `Vec` + `String::clone` allocations that the previous
/// `Vec<(&'static str, String)>` impl performed unconditionally —
/// string-bearing variants now borrow, integer-bearing variants
/// allocate exactly one `String` for the numeric text.
pub fn translate_with_locale_args_cow(
    locale: &str,
    key: &str,
    args: &[(&str, Cow<'_, str>)],
) -> String {
    let translated = translate_with_locale_cow(locale, key).into_owned();
    if args.is_empty() {
        return translated;
    }
    let keys: SmallVec<[&str; 4]> = args.iter().map(|(k, _)| *k).collect();
    let values: SmallVec<[String; 4]> = args.iter().map(|(_, v)| v.to_string()).collect();
    rust_i18n::replace_patterns(&translated, &keys, &values)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Save and restore the global locale around tests that may touch it.
    struct LocaleGuard {
        saved: String,
    }

    impl LocaleGuard {
        fn new() -> Self {
            Self {
                saved: rust_i18n::locale().to_string(),
            }
        }
    }

    impl Drop for LocaleGuard {
        fn drop(&mut self) {
            rust_i18n::set_locale(&self.saved);
        }
    }

    #[test]
    fn test_translate_with_locale_en() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale("en", "error.unknown"),
            "Unknown error"
        );
    }

    #[test]
    fn test_translate_with_locale_zh_cn() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(translate_with_locale("zh-CN", "error.unknown"), "未知错误");
    }

    #[test]
    fn test_translate_with_locale_args_en() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale_args(
                "en",
                "error.invalid_input",
                &[("value", "negative".to_string())]
            ),
            "Invalid input: negative"
        );
    }

    #[test]
    fn test_translate_with_locale_args_zh_cn() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale_args(
                "zh-CN",
                "error.invalid_input",
                &[("value", "negative".to_string())]
            ),
            "无效输入：negative"
        );
    }

    #[test]
    fn test_translate_with_locale_missing_key_returns_key() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        // Non-existent key returns the key itself (no panic, no empty string)
        assert_eq!(
            translate_with_locale("en", "error.nonexistent_key_xyz_123"),
            "error.nonexistent_key_xyz_123"
        );
    }

    #[test]
    fn test_translate_with_locale_unsupported_locale_falls_back() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        // Unsupported locale falls back to fallback locale ("en")
        let s = translate_with_locale("fr", "error.unknown");
        assert_eq!(s, "Unknown error");
    }

    #[test]
    fn test_translate_with_locale_args_empty_args() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale_args("en", "error.unknown", &[]),
            "Unknown error"
        );
    }

    #[test]
    fn test_translate_with_locale_args_named_arg() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale_args(
                "en",
                "error.clock_moved_backward",
                &[("last_timestamp", "123".to_string())]
            ),
            "Clock moved backward, last timestamp: 123"
        );
    }

    #[test]
    fn test_translate_with_locale_does_not_mutate_global_locale() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        // Translate in zh-CN
        let _ = translate_with_locale("zh-CN", "error.unknown");
        // Global locale should remain "en" — no race condition risk
        assert_eq!(&*rust_i18n::locale(), "en");
    }

    #[test]
    fn test_translate_with_locale_concurrent_safety() {
        // Simulate concurrent calls with different locales — each call should
        // return its own locale's translation, regardless of call ordering.
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");

        let en = translate_with_locale("en", "error.unknown");
        let zh = translate_with_locale("zh-CN", "error.unknown");
        let en2 = translate_with_locale("en", "error.unknown");
        let zh2 = translate_with_locale("zh-CN", "error.unknown");

        assert_eq!(en, "Unknown error");
        assert_eq!(zh, "未知错误");
        assert_eq!(en2, "Unknown error");
        assert_eq!(zh2, "未知错误");
    }

    /// M2 perf — `translate_with_locale_cow` returns `Cow::Borrowed`
    /// for static yml strings and never forces an allocation. The
    /// caller can `into_owned()` only when an owned `String` is
    /// actually needed.
    #[test]
    fn test_translate_with_locale_cow_borrowed_for_static_strings() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        let cow = translate_with_locale_cow("en", "error.unknown");
        // Either Borrowed (the static yml string) or Owned (fallback) is
        // valid depending on rust-i18n's internal storage; both must
        // produce the correct translation. The main invariant is that
        // the call returns a translation, not an empty string.
        assert_eq!(cow.as_ref(), "Unknown error");
    }

    /// M3 perf — `translate_with_locale_args_cow` accepts `Cow<str>`
    /// values (borrowed or owned) and produces the same output as the
    /// `String`-based variant.
    #[test]
    fn test_translate_with_locale_args_cow_equivalent_to_owned() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");

        let owned = translate_with_locale_args(
            "en",
            "error.invalid_input",
            &[("value", "negative".to_string())],
        );
        let borrowed = translate_with_locale_args_cow(
            "en",
            "error.invalid_input",
            &[("value", Cow::Borrowed("negative"))],
        );
        assert_eq!(owned, borrowed);
        assert_eq!(owned, "Invalid input: negative");
    }

    /// M3 perf — empty args path returns the translation verbatim,
    /// skipping the `replace_patterns` call entirely.
    #[test]
    fn test_translate_with_locale_args_cow_empty_args() {
        let _g = LocaleGuard::new();
        rust_i18n::set_locale("en");
        assert_eq!(
            translate_with_locale_args_cow("en", "error.unknown", &[]),
            "Unknown error"
        );
    }
}
