// Copyright © 2026 Kirky.X
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This module contains the authoritative protobuf code for gRPC services.
//
// NOTE: These files were originally generated by prost-build from
// protos/nebula_id.proto, but the build.rs and [build-dependencies] have been
// removed (build.rs was misplaced at src/build.rs, never executed by Cargo).
// These .rs files are now the authoritative source — manually maintained with
// `::sdforge::prost::` / `::sdforge::tonic::` path migration applied.
// Do NOT regenerate without re-applying the sdforge path migration.

pub mod nebula {
    pub mod id {
        pub mod v1 {
            include!("nebula/id/v1/nebula.id.v1.rs");
        }
    }
}
