// Copyright (c) 2025-2026 Kirky.X🌠
// SPDX-License-Identifier: Apache-2.0

// This module contains the authoritative protobuf code for gRPC services.
//
// NOTE: These files were originally generated by prost-build from
// protos/nebula_id.proto, but the build.rs and [build-dependencies] have been
// removed (build.rs was misplaced at src/build.rs, never executed by Cargo).
// These .rs files are now the authoritative source — manually maintained with
// `::sdforge::prost::` / `::sdforge::tonic::` path migration applied.
// Do NOT regenerate without re-applying the sdforge path migration.

pub mod nebula {
    pub mod id {
        pub mod v1 {
            include!("nebula/id/v1/nebula.id.v1.rs");
        }
    }
}
