// Copyright © 2026 Kirky.X
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use nebulaid::core::algorithm::AlgorithmRouter;
use nebulaid::core::config::Config;
#[cfg(feature = "etcd")]
use nebulaid::core::coordinator::{EtcdClientWrapper, EtcdClusterHealthMonitor};
use nebulaid::core::database::{self, ApiKeyRepository};
use nebulaid::core::types::Result;
use nebulaid::server::audit::AuditLogger;
use nebulaid::server::config::hot_reload::HotReloadConfig;
use nebulaid::server::config::management::{ConfigManagementService, ConfigManager};
use nebulaid::server::config::tls::TlsManager;
use nebulaid::server::grpc::GrpcServer;
use nebulaid::server::handlers::ApiHandlers;
use nebulaid::server::middleware::size_limit::create_size_limit_middleware;
use nebulaid::server::middleware::ApiKeyAuth;
use nebulaid::server::proto::nebula::id::v1::nebula_id_service_server::NebulaIdServiceServer;
use nebulaid::server::rate_limit::limiter::RateLimiter;
use nebulaid::server::router::create_router;
use nebulaid::server::sdforge_adapter::{init_sdforge, merge_sdforge_routes};
use std::env;
use std::net::SocketAddr;
use std::sync::Arc;
use tokio::net::TcpListener;
use tonic::transport::Server;
use tracing::warn;
use tracing::{error, info};
use tracing_subscriber::EnvFilter;

// Phase 8 ICU i18n — bin crate must call `i18n!` independently because
// `_rust_i18n_t!` (generated by `i18n!`) is `pub(crate)` visibility.
// Without this, `t!()` lookups in main.rs would resolve to
// `bin_crate::_rust_i18n_t!` which doesn't exist (rust-i18n-macro 3.x
// generates the helper macro with `pub(crate)` visibility).
#[macro_use]
extern crate rust_i18n;

i18n!("locales", fallback = "en");

const DEFAULT_CONFIG_PATH: &str = "config/config.toml";
const DEFAULT_SERVER_PORT: u16 = 8080;
const DEFAULT_GRPC_PORT: u16 = 50051;

/// 服务器配置
#[derive(Debug, Clone)]
pub struct ServerConfig {
    /// HTTP 服务端口
    pub http_port: u16,
    /// gRPC 服务端口
    pub grpc_port: u16,
    /// 工作线程数
    pub workers: usize,
    /// 关闭超时时间（秒）
    pub shutdown_timeout_secs: u64,
}

impl Default for ServerConfig {
    fn default() -> Self {
        let workers = std::thread::available_parallelism()
            .map(|p| p.get())
            .unwrap_or(1);
        Self {
            http_port: DEFAULT_SERVER_PORT,
            grpc_port: DEFAULT_GRPC_PORT,
            workers,
            shutdown_timeout_secs: 30,
        }
    }
}

async fn load_api_keys(
    _auth: &Arc<ApiKeyAuth>,
    repository: &Option<Arc<database::SeaOrmRepository>>,
    config: &Config,
) {
    use nebulaid::core::database::{ApiKeyRole, CreateApiKeyRequest};
    use uuid::Uuid;

    info!("{}", t!("log.main.loading_api_keys"));

    if let Some(ref repo) = repository {
        // First, create API key from environment variable if configured
        // Format: NEBULA_ADMIN_API_KEY_SECRET=your-secret-key
        let admin_key_secret_from_env = std::env::var("NEBULA_ADMIN_API_KEY_SECRET").ok();
        let admin_key_id_from_env = std::env::var("NEBULA_ADMIN_API_KEY_ID").ok();

        // Second, create API keys from config if configured
        // Config format: api_keys = [{ key_secret = "xxx", workspace = "global", role = "admin", rate_limit = 100000, name = "Admin" }]
        let configured_keys = if !config.auth.api_keys.is_empty() {
            Some(config.auth.api_keys.clone())
        } else {
            None
        };

        // If configured via env or config, create the key (key_id generated internally)
        if let Some(ref secret) = admin_key_secret_from_env {
            info!("{}", t!("log.main.creating_admin_api_key_from_env"));

            let request = CreateApiKeyRequest {
                workspace_id: None,
                name: "admin".to_string(),
                description: Some("Admin API key from environment".to_string()),
                role: ApiKeyRole::Admin,
                rate_limit: Some(100000),
                expires_at: None,
                key_secret: Some(secret.to_string()),
                key_id: admin_key_id_from_env,
            };

            match repo.create_api_key(&request).await {
                Ok(key) => {
                    info!(
                        "{}",
                        t!("log.main.admin_api_key_created", key_id = key.key.key_id)
                    );
                }
                Err(e) => {
                    if !e.to_string().contains("duplicate key") {
                        error!("{}", t!("log.main.admin_api_key_create_failed", error = e));
                    }
                }
            }
        } else if let Some(ref keys) = configured_keys {
            if let Some(first_key) = keys.first() {
                info!("{}", t!("log.main.creating_api_key_from_config"));

                let role = match first_key.role.to_lowercase().as_str() {
                    "admin" => ApiKeyRole::Admin,
                    _ => ApiKeyRole::User,
                };

                let request = CreateApiKeyRequest {
                    workspace_id: if first_key.workspace == "global" {
                        None
                    } else {
                        Some(Uuid::parse_str(&first_key.workspace).unwrap_or(Uuid::nil()))
                    },
                    name: first_key.name.clone(),
                    description: Some(format!("Configured via config, role: {}", first_key.role)),
                    role,
                    rate_limit: Some(first_key.rate_limit as i32),
                    expires_at: None,
                    key_secret: Some(first_key.key_secret.clone()),
                    key_id: Some(first_key.key_id.clone()),
                };

                match repo.create_api_key(&request).await {
                    Ok(key) => {
                        info!(
                            "{}",
                            t!(
                                "log.main.api_key_created_from_config",
                                key_id = key.key.key_id,
                                role = first_key.role
                            )
                        );
                    }
                    Err(e) => {
                        if !e.to_string().contains("duplicate key") {
                            warn!(
                                "{}",
                                t!("log.main.api_key_create_from_config_failed", error = e)
                            );
                        }
                    }
                }
            }
        } else {
            // No configuration, check if admin key already exists
            match repo.get_admin_api_key(Uuid::nil()).await {
                Ok(Some(admin_key)) => {
                    info!(
                        key_id = ?admin_key.key_id,
                        workspace_id = ?admin_key.workspace_id,
                        "{}",
                        t!("log.main.existing_admin_api_key_found")
                    );
                }
                Ok(None) => {
                    // Generate new admin API key
                    let admin_request = CreateApiKeyRequest {
                        workspace_id: None,
                        name: "admin".to_string(),
                        description: Some("Default Admin API Key".to_string()),
                        role: ApiKeyRole::Admin,
                        rate_limit: Some(100000),
                        expires_at: None,
                        key_secret: None,
                        key_id: None,
                    };
                    match repo.create_api_key(&admin_request).await {
                        Ok(key) => {
                            info!(
                                "{}",
                                t!(
                                    "log.main.admin_api_key_created_no_workspace",
                                    key_id = key.key.key_id
                                )
                            );

                            let is_production = nebulaid::core::config::is_production();

                            if !is_production {
                                // WARN: Print secret to console only once - user must save it
                                println!("\n╔════════════════════════════════════════════════════════════════════╗");
                                println!("║           ⚠️  ADMIN API KEY GENERATED - SAVE NOW!              ║");
                                println!("╠════════════════════════════════════════════════════════════════════╣");
                                println!(
                                    "║  Key ID: {}                                                ║",
                                    key.key.key_id
                                );
                                println!(
                                    "║  Secret: {}                                    ║",
                                    key.key_secret
                                );
                                println!("║                                                                    ║");
                                println!("║  ⚠️  THIS IS THE ONLY TIME THE SECRET WILL BE SHOWN!           ║");
                                println!("║  Save it securely - you will need it for API authentication.    ║");
                                println!("╚════════════════════════════════════════════════════════════════════╝\n");
                                tracing::warn!("{}", t!("log.main.admin_api_key_secret_printed"));
                            } else {
                                tracing::warn!(
                                    "{}",
                                    t!("log.main.admin_api_key_generated_no_print")
                                );
                            }
                        }
                        Err(e) => {
                            error!("{}", t!("log.main.admin_api_key_create_failed", error = e));
                        }
                    }
                }
                Err(e) => {
                    error!("{}", t!("log.main.admin_api_key_check_failed", error = e));
                }
            }
        }

        // Add test API key in development mode only if no configuration provided
        #[cfg(debug_assertions)]
        if admin_key_secret_from_env.is_none() && configured_keys.is_none() {
            let test_request = CreateApiKeyRequest {
                workspace_id: None,
                name: "Test Admin API Key".to_string(),
                description: Some("Default test admin API key".to_string()),
                role: ApiKeyRole::Admin,
                rate_limit: Some(10000),
                expires_at: None,
                key_secret: None,
                key_id: None,
            };
            match repo.create_api_key(&test_request).await {
                Ok(key) => {
                    info!(
                        "{}",
                        t!(
                            "log.main.test_admin_api_key_created",
                            key_id = key.key.key_id
                        )
                    );
                }
                Err(e) => {
                    if !e.to_string().contains("duplicate key") {
                        warn!("{}", t!("log.main.test_api_key_create_failed", error = e));
                    }
                }
            }
        }
    } else {
        warn!("{}", t!("log.main.no_database_connection"));
    }
}

#[cfg(feature = "etcd")]
async fn create_id_generator(
    config: &Config,
    audit_logger: Arc<AuditLogger>,
    etcd_health_monitor: Option<Arc<EtcdClusterHealthMonitor>>,
) -> Result<Arc<AlgorithmRouter>> {
    info!("{}", t!("log.main.id_generators_initializing"));

    let audit_logger_for_core: nebulaid::core::algorithm::DynAuditLogger =
        audit_logger as Arc<dyn nebulaid::core::algorithm::AuditLogger>;

    // Create CPU monitor
    let cpu_monitor = Arc::new(nebulaid::core::algorithm::CpuMonitor::new());
    let router = AlgorithmRouter::new(config.clone(), Some(audit_logger_for_core));

    let router = router.with_cpu_monitor(cpu_monitor);
    let router = if let Some(monitor) = etcd_health_monitor {
        Arc::new(router.with_etcd_health_monitor(monitor))
    } else {
        Arc::new(router)
    };

    router.initialize().await?;

    info!("{}", t!("log.main.id_generators_initialized"));
    Ok(router)
}

#[cfg(not(feature = "etcd"))]
async fn create_id_generator(
    config: &Config,
    audit_logger: Arc<AuditLogger>,
    _etcd_health_monitor: Option<Arc<()>>,
) -> Result<Arc<AlgorithmRouter>> {
    info!(
        "{}",
        t!("log.main.id_generators_initializing_etcd_disabled")
    );

    let audit_logger_for_core: nebulaid::core::algorithm::DynAuditLogger =
        audit_logger as Arc<dyn nebulaid::core::algorithm::AuditLogger>;

    // Create CPU monitor
    let cpu_monitor = Arc::new(nebulaid::core::algorithm::CpuMonitor::new());
    let router = AlgorithmRouter::new(config.clone(), Some(audit_logger_for_core));
    let router = router.with_cpu_monitor(cpu_monitor);
    let router = Arc::new(router);

    router.initialize().await?;

    info!("{}", t!("log.main.id_generators_initialized"));
    Ok(router)
}

async fn start_http_server(
    _config: ServerConfig,
    handlers: Arc<ApiHandlers>,
    auth: Arc<ApiKeyAuth>,
    rate_limiter: Arc<RateLimiter>,
    audit_logger: Arc<AuditLogger>,
    _config_service: Arc<dyn ConfigManagementService>,
    tls_manager: Option<Arc<TlsManager>>,
) -> Result<()> {
    let addr = SocketAddr::from(([0, 0, 0, 0], DEFAULT_SERVER_PORT));

    let router = create_router(handlers, auth, rate_limiter, audit_logger)
        .await
        .layer(create_size_limit_middleware())
        .merge(merge_sdforge_routes(axum::Router::new()));

    // 检查是否启用 HTTPS (暂时回退到普通 HTTP，TLS 功能待完善)
    if let Some(ref tls) = tls_manager {
        if tls.is_http_enabled() {
            info!("{}", t!("log.main.https_enabled_http_fallback"));
        }
    }

    // 回退到普通 HTTP
    info!("{}", t!("log.main.starting_http_server", addr = addr));
    let listener = TcpListener::bind(addr).await?;

    axum::serve(listener, router)
        .with_graceful_shutdown(async {
            tokio::signal::ctrl_c().await.ok();
            info!("{}", t!("log.main.shutting_down_http_server"));
        })
        .await?;

    Ok(())
}

async fn start_grpc_server(
    config: ServerConfig,
    handlers: Arc<ApiHandlers>,
    tls_manager: Option<Arc<TlsManager>>,
) -> Result<()> {
    let grpc_addr = SocketAddr::from(([0, 0, 0, 0], config.grpc_port));
    info!("{}", t!("log.main.starting_grpc_server", addr = grpc_addr));
    info!(
        "{}",
        t!("log.main.configured_grpc_port", port = config.grpc_port)
    );

    let grpc_server = GrpcServer::new(handlers);

    let shutdown = async {
        tokio::signal::ctrl_c().await.ok();
        info!("{}", t!("log.main.shutting_down_grpc_server"));
    };

    let mut server_builder = Server::builder();

    if let Some(ref tls) = tls_manager {
        if tls.is_grpc_enabled() {
            info!("{}", t!("log.main.grpc_tls_enabled"));
            if let Some(grpc_tls_config) = tls.grpc_tls_config() {
                let config = grpc_tls_config.as_ref().clone();
                server_builder = server_builder.tls_config(config).map_err(|e| {
                    nebulaid::core::types::CoreError::InternalError(format!(
                        "TLS config error: {}",
                        e
                    ))
                })?;
            }
        }
    }

    server_builder
        .add_service(NebulaIdServiceServer::new(grpc_server))
        .serve_with_shutdown(grpc_addr, shutdown)
        .await
        .map_err(|e| {
            nebulaid::core::types::CoreError::InternalError(format!("gRPC server error: {}", e))
        })?;

    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("Failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("Failed to install signal handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = terminate => {},
    }
}

/// ARCH-LOW-003 修复：抽取 etcd / non-etcd 分支共用的 ApiHandlers 构造逻辑。
///
/// 原代码在两个 cfg 分支重复调用 `ApiHandlers::with_api_key_repository`
/// + `.with_key_rotation_grace_period`，未来新增 builder 方法需同步改两处
/// （霰弹手术气味）。本 helper 集中构造逻辑。
#[allow(clippy::too_many_arguments, clippy::doc_lazy_continuation)]
fn build_api_handlers(
    id_generator: Arc<nebulaid::core::algorithm::AlgorithmRouter>,
    cs: Arc<dyn ConfigManagementService>,
    repo: Arc<dyn ApiKeyRepository>,
    grace_period_seconds: u64,
) -> ApiHandlers {
    ApiHandlers::with_api_key_repository(id_generator, cs, repo)
        .with_key_rotation_grace_period(grace_period_seconds)
}

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_target(false)
        .with_env_filter(EnvFilter::from_default_env())
        .json()
        .init();

    // Phase 8 ICU i18n — initialize default locale before any t!() lookup.
    nebulaid::core::i18n::init_i18n("en");

    info!("{}", t!("log.main.starting_service"));
    info!(
        "{}",
        t!("log.main.version", version = env!("CARGO_PKG_VERSION"))
    );

    // Initialize sdforge plugins so inventory-registered routes are linked
    // into the final binary (prevents linker stripping). Must be called
    // before merge_sdforge_routes builds the axum Router.
    let plugin_counts = init_sdforge();
    info!(
        routes = plugin_counts.routes,
        "{}",
        t!("log.main.sdforge_plugins_initialized")
    );

    // Parse command line arguments
    let args: Vec<String> = env::args().collect();
    let config_path = if args.len() > 2 && args[1] == "--config" {
        args[2].clone()
    } else {
        DEFAULT_CONFIG_PATH.to_string()
    };

    info!("{}", t!("log.main.loading_config", path = config_path));

    // Load config from file first, then merge with environment variables
    let mut config = match Config::load_from_file(&config_path) {
        Ok(c) => c,
        Err(e) => {
            error!("{}", t!("log.main.config_load_failed", error = e));
            Config::default()
        }
    };

    // Apply environment variable overrides
    config.merge(Config::load_from_env().unwrap_or_default());
    info!("{}", t!("log.main.config_loaded"));

    let server_config = ServerConfig {
        http_port: config.app.http_port,
        grpc_port: config.app.grpc_port,
        workers: std::thread::available_parallelism()
            .map(|p| p.get())
            .unwrap_or(1),
        shutdown_timeout_secs: 30,
    };

    info!(
        "{}",
        t!(
            "log.main.starting_server_on_ports",
            http_port = server_config.http_port,
            grpc_port = server_config.grpc_port
        )
    );

    // Initialize database connection first (needed for API key auth)
    info!("{}", t!("log.main.connecting_to_database"));
    let db_connection = match database::create_connection(&config.database).await {
        Ok(conn) => {
            info!("{}", t!("log.main.database_connected"));

            // Run auto migrations to create tables
            if let Err(e) = database::run_migrations(&conn).await {
                error!("{}", t!("log.main.migrations_failed", error = e));
                error!("{}", t!("log.main.shutting_down"));
                std::process::exit(1);
            }

            Some(conn)
        }
        Err(e) => {
            error!("{}", t!("log.main.database_connect_failed", error = e));
            error!("{}", t!("log.main.check_database_url"));
            error!("{}", t!("log.main.shutting_down"));
            std::process::exit(1);
        }
    };

    let repository: Option<Arc<database::SeaOrmRepository>> = if let Some(conn) = db_connection {
        // M8 修复：注入分布式锁，避免 allocate_segment 在无锁降级时产生重复 ID。
        // 默认构建（无 etcd feature）使用 LocalDistributedLock（进程内互斥）。
        #[cfg(not(feature = "etcd"))]
        let lock: std::sync::Arc<
            dyn nebulaid::core::coordinator::DistributedLock + Send + Sync,
        > = std::sync::Arc::new(nebulaid::core::coordinator::LocalDistributedLock::new());
        // etcd feature 构建下，若 etcd 端点已配置，先创建 EtcdClientWrapper，
        // 再用它构造 EtcdDistributedLock；任一步失败回退到 LocalDistributedLock。
        #[cfg(feature = "etcd")]
        let lock: std::sync::Arc<
            dyn nebulaid::core::coordinator::DistributedLock + Send + Sync,
        > = if !config.etcd.endpoints.is_empty() {
            match nebulaid::core::coordinator::EtcdClientWrapper::new(config.etcd.endpoints.clone())
                .await
            {
                Ok(client) => {
                    let client: std::sync::Arc<dyn nebulaid::core::coordinator::EtcdClientOps> =
                        std::sync::Arc::new(client);
                    match nebulaid::core::coordinator::EtcdDistributedLock::new(
                        client,
                        "nebulaid-segment-lock".to_string(),
                    )
                    .await
                    {
                        Ok(etcd_lock) => std::sync::Arc::new(etcd_lock),
                        Err(_) => {
                            warn!("Failed to create EtcdDistributedLock, falling back to LocalDistributedLock");
                            std::sync::Arc::new(
                                nebulaid::core::coordinator::LocalDistributedLock::new(),
                            )
                        }
                    }
                }
                Err(_) => {
                    warn!(
                        "Failed to create EtcdClientWrapper, falling back to LocalDistributedLock"
                    );
                    std::sync::Arc::new(nebulaid::core::coordinator::LocalDistributedLock::new())
                }
            }
        } else {
            warn!(
                "Etcd endpoints not configured, using LocalDistributedLock (single-process only)"
            );
            std::sync::Arc::new(nebulaid::core::coordinator::LocalDistributedLock::new())
        };

        // tiangang C1 修复：生产环境强制校验 api_key_salt 非空且非弱默认值。
        // 规则 12（失败必须显性化）：校验失败时 panic，禁止弱 pepper 静默放行。
        if nebulaid::core::config::is_production() {
            let salt = &config.auth.api_key_salt;
            if salt.is_empty()
                || salt.len() < 16
                || salt == "test"
                || salt == "test-secret-value-12345"
            {
                panic!(
                    "{}",
                    t!(
                        "error.main.invalid_api_key_salt_production",
                        env = "NEBULA_API_KEY_SALT"
                    )
                );
            }
        }

        let repo = Arc::new(
            database::SeaOrmRepository::new(conn, config.auth.api_key_salt.clone())
                .with_distributed_lock(lock),
        );
        info!("{}", t!("log.main.database_repository_initialized"));
        Some(repo)
    } else {
        None
    };

    info!(
        "{}",
        t!("log.main.auth_enabled", enabled = config.auth.enabled)
    );

    // Create API key auth with repository for database-backed storage
    // Phase 9 T043 (HIGH H3) — configure trusted proxies so the auth
    // middleware only honors `X-Forwarded-For` / `X-Real-IP` when the
    // direct peer IP is in `NEBULA_TRUSTED_PROXIES`. Default: empty
    // (no headers trusted, all clients identified by TCP peer IP).
    let trusted_proxies: Vec<std::net::IpAddr> = std::env::var("NEBULA_TRUSTED_PROXIES")
        .ok()
        .map(|s| s.split(',').filter_map(|p| p.trim().parse().ok()).collect())
        .unwrap_or_default();
    let auth: Arc<ApiKeyAuth> = if let Some(ref repo) = repository {
        Arc::new(
            ApiKeyAuth::new(repo.clone(), config.auth.enabled)
                .with_trusted_proxies(trusted_proxies.clone()),
        )
    } else {
        error!("{}", t!("log.main.fatal_api_key_auth_requires_database"));
        std::process::exit(1);
    };
    let _ = trusted_proxies; // also consumed by router.rs via env var
    load_api_keys(&auth, &repository, &config).await;

    // Initialize audit logger and config (used by both etcd and non-etcd modes)
    let audit_logger = Arc::new(AuditLogger::new(config.rate_limit.default_rps as usize));
    let hot_config = Arc::new(HotReloadConfig::new(
        config.clone(),
        "config/config.toml".to_string(),
    ));

    #[cfg(feature = "etcd")]
    {
        info!("{}", t!("log.main.initializing_etcd_health_monitor"));
        let etcd_cache_path = format!("./data/etcd_cache_{}.json", config.app.dc_id);

        // F-01 修复：生产路径注入 EtcdClientWrapper，让 check_etcd_health 走 trait 抽象层。
        // 尝试建立长连接 client；失败则回退到 new()（每次检查新建 client 的 fallback 路径）。
        let etcd_health_monitor = if !config.etcd.endpoints.is_empty() {
            match EtcdClientWrapper::new(config.etcd.endpoints.clone()).await {
                Ok(client) => {
                    info!("{}", t!("log.main.etcd_client_wrapper_initialized"));
                    Arc::new(EtcdClusterHealthMonitor::new_with_client(
                        config.etcd.clone(),
                        etcd_cache_path,
                        Arc::new(client),
                    ))
                }
                Err(e) => {
                    warn!(
                        "{}",
                        t!("log.main.etcd_client_wrapper_init_failed", error = e)
                    );
                    Arc::new(EtcdClusterHealthMonitor::new(
                        config.etcd.clone(),
                        etcd_cache_path,
                    ))
                }
            }
        } else {
            Arc::new(EtcdClusterHealthMonitor::new(
                config.etcd.clone(),
                etcd_cache_path,
            ))
        };

        if let Err(e) = etcd_health_monitor.load_local_cache().await {
            warn!("{}", t!("log.main.etcd_local_cache_load_failed", error = e));
        }

        info!("{}", t!("log.main.etcd_health_monitor_initialized"));

        let id_generator = create_id_generator(
            &config,
            audit_logger.clone(),
            Some(etcd_health_monitor.clone()),
        )
        .await?;

        let (handlers, config_service) = if let Some(ref repo) = repository {
            let cs = Arc::new(ConfigManager::with_repository(
                hot_config,
                id_generator.clone(),
                repo.clone(),
                repo.clone(),
                repo.clone(),
            ));
            let h = Arc::new(build_api_handlers(
                id_generator.clone(),
                cs.clone(),
                repo.clone(),
                config.auth.key_rotation_grace_period_seconds,
            ));
            (h, cs)
        } else {
            let cs = Arc::new(ConfigManager::new(hot_config, id_generator.clone()));
            let h = Arc::new(ApiHandlers::new(id_generator.clone(), cs.clone()));
            (h, cs)
        };

        let rate_limiter = Arc::new(RateLimiter::new(
            config.rate_limit.default_rps,
            config.rate_limit.burst_size,
        ));

        let mut tls_manager = TlsManager::new(config.tls.clone());
        if let Err(e) = tls_manager.initialize().await {
            error!("{}", t!("log.main.tls_init_failed", error = e));
            info!("{}", t!("log.main.tls_disabled"));
        }
        let tls_manager = if tls_manager.is_http_enabled() || tls_manager.is_grpc_enabled() {
            Some(Arc::new(tls_manager))
        } else {
            None
        };

        info!("{}", t!("log.main.starting_degradation_check"));
        let degradation_manager = id_generator.get_degradation_manager();
        degradation_manager.start_background_check();

        info!("{}", t!("log.main.server_initialized_starting"));

        let http_server = tokio::spawn(start_http_server(
            server_config.clone(),
            handlers.clone(),
            auth.clone(),
            rate_limiter.clone(),
            audit_logger.clone(),
            config_service.clone(),
            tls_manager.clone(),
        ));
        let grpc_server = tokio::spawn(start_grpc_server(server_config, handlers, tls_manager));

        tokio::select! {
            http_result = http_server => {
                match http_result {
                    Ok(Ok(())) => info!(
                        "{}",
                        t!("log.main.http_server_stopped")
                    ),
                    Ok(Err(e)) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.http_server_error",
                                error = e
                            )
                        );
                        return Err(e);
                    }
                    Err(e) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.http_server_panic",
                                error = e
                            )
                        );
                        return Err(nebulaid::core::types::CoreError::InternalError(format!("HTTP server panic: {}", e)));
                    }
                }
            }
            grpc_result = grpc_server => {
                match grpc_result {
                    Ok(Ok(())) => info!(
                        "{}",
                        t!("log.main.grpc_server_stopped")
                    ),
                    Ok(Err(e)) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.grpc_server_error",
                                error = e
                            )
                        );
                        return Err(e);
                    }
                    Err(e) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.grpc_server_panic",
                                error = e
                            )
                        );
                        return Err(nebulaid::core::types::CoreError::InternalError(format!("gRPC server panic: {}", e)));
                    }
                }
            }
            _ = shutdown_signal() => {
                info!(
                    "{}",
                    t!("log.main.shutdown_signal_received")
                );
            }
        }

        Ok(())
    }

    #[cfg(not(feature = "etcd"))]
    {
        info!("{}", t!("log.main.etcd_disabled"));

        let audit_logger_for_core: nebulaid::core::algorithm::DynAuditLogger =
            audit_logger.clone() as Arc<dyn nebulaid::core::algorithm::AuditLogger>;
        let router = AlgorithmRouter::new(config.clone(), Some(audit_logger_for_core));
        let _router = Arc::new(router);

        let id_generator = create_id_generator(&config, audit_logger.clone(), None).await?;

        let (handlers, config_service) = if let Some(ref repo) = repository {
            let cs = Arc::new(ConfigManager::with_repository(
                hot_config,
                id_generator.clone(),
                repo.clone(),
                repo.clone(),
                repo.clone(),
            ));
            let h = Arc::new(build_api_handlers(
                id_generator.clone(),
                cs.clone(),
                repo.clone(),
                config.auth.key_rotation_grace_period_seconds,
            ));
            (h, cs)
        } else {
            let cs = Arc::new(ConfigManager::new(hot_config, id_generator.clone()));
            let h = Arc::new(ApiHandlers::new(id_generator.clone(), cs.clone()));
            (h, cs)
        };

        let rate_limiter = Arc::new(RateLimiter::new(
            config.rate_limit.default_rps,
            config.rate_limit.burst_size,
        ));

        let mut tls_manager = TlsManager::new(config.tls.clone());
        if let Err(e) = tls_manager.initialize().await {
            error!("{}", t!("log.main.tls_init_failed", error = e));
            info!("{}", t!("log.main.tls_disabled"));
        }
        let tls_manager = if tls_manager.is_http_enabled() || tls_manager.is_grpc_enabled() {
            Some(Arc::new(tls_manager))
        } else {
            None
        };

        info!("{}", t!("log.main.starting_degradation_check"));
        let degradation_manager = id_generator.get_degradation_manager();
        degradation_manager.start_background_check();

        info!("{}", t!("log.main.server_initialized_starting"));

        let http_server = tokio::spawn(start_http_server(
            server_config.clone(),
            handlers.clone(),
            auth.clone(),
            rate_limiter.clone(),
            audit_logger.clone(),
            config_service.clone(),
            tls_manager.clone(),
        ));
        let grpc_server = tokio::spawn(start_grpc_server(server_config, handlers, tls_manager));

        tokio::select! {
            http_result = http_server => {
                match http_result {
                    Ok(Ok(())) => info!(
                        "{}",
                        t!("log.main.http_server_stopped")
                    ),
                    Ok(Err(e)) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.http_server_error",
                                error = e
                            )
                        );
                        return Err(e);
                    }
                    Err(e) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.http_server_panic",
                                error = e
                            )
                        );
                        return Err(nebulaid::core::types::CoreError::InternalError(format!("HTTP server panic: {}", e)));
                    }
                }
            }
            grpc_result = grpc_server => {
                match grpc_result {
                    Ok(Ok(())) => info!(
                        "{}",
                        t!("log.main.grpc_server_stopped")
                    ),
                    Ok(Err(e)) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.grpc_server_error",
                                error = e
                            )
                        );
                        return Err(e);
                    }
                    Err(e) => {
                        error!(
                            "{}",
                            t!(
                                "log.main.grpc_server_panic",
                                error = e
                            )
                        );
                        return Err(nebulaid::core::types::CoreError::InternalError(format!("gRPC server panic: {}", e)));
                    }
                }
            }
            _ = shutdown_signal() => {
                info!(
                    "{}",
                    t!("log.main.shutdown_signal_received")
                );
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nebulaid::core::algorithm::AlgorithmRouter;
    use nebulaid::core::config::Config;
    use nebulaid::server::config::hot_reload::HotReloadConfig;
    use std::sync::Arc;

    /// Setup test environment - must be called at the start of each test
    fn setup_test_env() {
        std::env::set_var("NEBULA_DATABASE_PASSWORD", "test_password");
    }

    #[tokio::test]
    async fn test_server_config_default() {
        let config = ServerConfig::default();
        assert_eq!(config.http_port, DEFAULT_SERVER_PORT);
        assert!(config.workers > 0);
        assert_eq!(config.shutdown_timeout_secs, 30);
    }

    #[tokio::test]
    async fn test_create_router_with_handlers() {
        setup_test_env();
        use async_trait::async_trait;

        #[derive(Clone)]
        struct MockApiKeyRepo;

        #[async_trait]
        impl database::ApiKeyRepository for MockApiKeyRepo {
            async fn create_api_key(
                &self,
                _request: &database::CreateApiKeyRequest,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_secret".to_string(),
                })
            }

            async fn get_api_key_by_id(
                &self,
                _key_id: &str,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn validate_api_key(
                &self,
                _key_id: &str,
                _key_secret: &str,
            ) -> nebulaid::core::types::Result<Option<(Option<uuid::Uuid>, database::ApiKeyRole)>>
            {
                Ok(None)
            }

            async fn list_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
                _limit: Option<u32>,
                _offset: Option<u32>,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }

            async fn delete_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn revoke_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn update_last_used(
                &self,
                _key: uuid::Uuid,
            ) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn get_admin_api_key(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn count_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            async fn rotate_api_key(
                &self,
                _key_id: &str,
                _grace_period_seconds: u64,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_rotated_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Rotated Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_rotated_secret".to_string(),
                })
            }

            async fn get_keys_older_than(
                &self,
                _age_threshold_days: i64,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }
        }

        let config = Config::default();
        let audit_logger: Arc<dyn nebulaid::core::algorithm::AuditLogger> =
            Arc::new(AuditLogger::new(10000));
        let router = AlgorithmRouter::new(config.clone(), Some(audit_logger));
        let router = Arc::new(router);
        let hot_config = Arc::new(HotReloadConfig::new(
            config.clone(),
            "config/config.toml".to_string(),
        ));
        let config_service = Arc::new(ConfigManager::new(hot_config, router.clone()));
        let handlers = Arc::new(ApiHandlers::with_api_key_repository(
            router,
            config_service,
            Arc::new(MockApiKeyRepo),
        ));
        let auth = Arc::new(ApiKeyAuth::new(Arc::new(MockApiKeyRepo), true));
        let rate_limiter = Arc::new(RateLimiter::new(10000, 100));
        let audit_logger = Arc::new(AuditLogger::new(10000));

        let _router = create_router(handlers, auth, rate_limiter, audit_logger).await;
    }

    #[tokio::test]
    async fn test_graceful_shutdown() {
        setup_test_env();
        use async_trait::async_trait;

        #[derive(Clone)]
        struct MockApiKeyRepo;

        #[async_trait]
        impl database::ApiKeyRepository for MockApiKeyRepo {
            async fn create_api_key(
                &self,
                _request: &database::CreateApiKeyRequest,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_secret".to_string(),
                })
            }

            async fn get_api_key_by_id(
                &self,
                _key_id: &str,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn validate_api_key(
                &self,
                _key_id: &str,
                _key_secret: &str,
            ) -> nebulaid::core::types::Result<Option<(Option<uuid::Uuid>, database::ApiKeyRole)>>
            {
                Ok(None)
            }

            async fn list_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
                _limit: Option<u32>,
                _offset: Option<u32>,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }

            async fn delete_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn revoke_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn update_last_used(
                &self,
                _key: uuid::Uuid,
            ) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn get_admin_api_key(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn count_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            async fn rotate_api_key(
                &self,
                _key_id: &str,
                _grace_period_seconds: u64,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_rotated_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Rotated Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_rotated_secret".to_string(),
                })
            }

            async fn get_keys_older_than(
                &self,
                _age_threshold_days: i64,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }
        }

        let config = Config::default();
        let audit_logger: Arc<dyn nebulaid::core::algorithm::AuditLogger> =
            Arc::new(AuditLogger::new(10000));
        let router = AlgorithmRouter::new(config.clone(), Some(audit_logger));
        let router = Arc::new(router);
        let hot_config = Arc::new(HotReloadConfig::new(
            config.clone(),
            "config/config.toml".to_string(),
        ));
        let config_service = Arc::new(ConfigManager::new(hot_config, router.clone()));
        let handlers = Arc::new(ApiHandlers::with_api_key_repository(
            router,
            config_service.clone(),
            Arc::new(MockApiKeyRepo),
        ));
        let auth = Arc::new(ApiKeyAuth::new(Arc::new(MockApiKeyRepo), true));
        let rate_limiter = Arc::new(RateLimiter::new(10000, 100));
        let audit_logger = Arc::new(AuditLogger::new(10000));

        let server_config = ServerConfig {
            http_port: 0,
            grpc_port: 0,
            workers: 1,
            shutdown_timeout_secs: 1,
        };

        let server = tokio::spawn(async move {
            start_http_server(
                server_config,
                handlers,
                auth,
                rate_limiter,
                audit_logger,
                config_service,
                None,
            )
            .await
        });

        tokio::time::sleep(std::time::Duration::from_millis(100)).await;

        let _ = tokio::time::timeout(std::time::Duration::from_secs(2), shutdown_signal()).await;

        server.abort();
    }
}
