// Copyright © 2026 Kirky.X
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use nebulaid::core::algorithm::AlgorithmRouter;
use nebulaid::core::config::{resolve_startup_config, Config, Environment, StartupConfig};
#[cfg(feature = "etcd")]
use nebulaid::core::coordinator::{EtcdClientWrapper, EtcdClusterHealthMonitor, WorkerIdAllocator};
use nebulaid::core::database::{self, ApiKeyRepository};
use nebulaid::core::types::Result;
use nebulaid::server::audit::AuditLogger;
use nebulaid::server::config::hot_reload::HotReloadConfig;
use nebulaid::server::config::management::{ConfigManagementService, ConfigManager};
use nebulaid::server::config::tls::{DualListener, PeerAddr, TlsManager};
use nebulaid::server::grpc::GrpcServer;
use nebulaid::server::handlers::ApiHandlers;
use nebulaid::server::middleware::size_limit::create_size_limit_middleware;
use nebulaid::server::middleware::ApiKeyAuth;
use nebulaid::server::proto::nebula::id::v1::nebula_id_service_server::NebulaIdServiceServer;
use nebulaid::server::rate_limit::limiter::RateLimiter;
use nebulaid::server::router::create_router_with_rate_limit;
use nebulaid::server::sdforge_adapter::{init_sdforge, merge_sdforge_routes};
use sdforge::tonic::transport::Server;
use std::env;
use std::net::SocketAddr;
use std::sync::Arc;
use tracing::warn;
use tracing::{error, info};

// Phase 8 ICU i18n — bin crate must call `i18n!` independently because
// `_rust_i18n_t!` (generated by `i18n!`) is `pub(crate)` visibility.
// Without this, `t!()` lookups in main.rs would resolve to
// `bin_crate::_rust_i18n_t!` which doesn't exist (rust-i18n-macro 3.x
// generates the helper macro with `pub(crate)` visibility).
#[macro_use]
extern crate rust_i18n;

i18n!("locales", fallback = "en");

const DEFAULT_CONFIG_PATH: &str = "config/config.toml";

/// 服务器配置
///
/// 端口默认值唯一归属 `core::config::AppConfig::default()`（8080/9091），
/// 此处经 `AppConfig::default()` 派生，禁止再引入本地端口常量。
#[derive(Debug, Clone)]
pub struct ServerConfig {
    /// HTTP 服务端口
    pub http_port: u16,
    /// gRPC 服务端口
    pub grpc_port: u16,
    /// 工作线程数
    pub workers: usize,
    /// 关闭超时时间（秒）
    pub shutdown_timeout_secs: u64,
}

impl Default for ServerConfig {
    fn default() -> Self {
        let app = nebulaid::core::config::AppConfig::default();
        let workers = std::thread::available_parallelism()
            .map(|p| p.get())
            .unwrap_or(1);
        Self {
            http_port: app.http_port,
            grpc_port: app.grpc_port,
            workers,
            shutdown_timeout_secs: 30,
        }
    }
}

async fn load_api_keys(
    _auth: &Arc<ApiKeyAuth>,
    repository: &Option<Arc<database::SeaOrmRepository>>,
    config: &Config,
) {
    use nebulaid::core::database::{ApiKeyRole, CreateApiKeyRequest};
    use uuid::Uuid;

    info!("{}", t!("log.main.loading_api_keys"));

    if let Some(ref repo) = repository {
        // First, create API key from environment variable if configured
        // Format: NEBULA_ADMIN_API_KEY_SECRET=your-secret-key
        let admin_key_secret_from_env = std::env::var("NEBULA_ADMIN_API_KEY_SECRET").ok();
        let admin_key_id_from_env = std::env::var("NEBULA_ADMIN_API_KEY_ID").ok();

        // Second, create API keys from config if configured
        // Config format: api_keys = [{ key_secret = "xxx", workspace = "global", role = "admin", rate_limit = 100000, name = "Admin" }]
        let configured_keys = if !config.auth.api_keys.is_empty() {
            Some(config.auth.api_keys.clone())
        } else {
            None
        };

        // If configured via env or config, create the key (key_id generated internally)
        if let Some(ref secret) = admin_key_secret_from_env {
            info!("{}", t!("log.main.creating_admin_api_key_from_env"));

            let request = CreateApiKeyRequest {
                workspace_id: None,
                name: "admin".to_string(),
                description: Some("Admin API key from environment".to_string()),
                role: ApiKeyRole::Admin,
                rate_limit: Some(100000),
                expires_at: None,
                key_secret: Some(secret.to_string()),
                key_id: admin_key_id_from_env,
            };

            match repo.create_api_key(&request).await {
                Ok(key) => {
                    info!(
                        "{}",
                        t!("log.main.admin_api_key_created", key_id = key.key.key_id)
                    );
                }
                Err(e) => {
                    if !e.to_string().contains("duplicate key") {
                        error!("{}", t!("log.main.admin_api_key_create_failed", error = e));
                    }
                }
            }
        } else if let Some(ref keys) = configured_keys {
            if let Some(first_key) = keys.first() {
                info!("{}", t!("log.main.creating_api_key_from_config"));

                let role = match first_key.role.to_lowercase().as_str() {
                    "admin" => ApiKeyRole::Admin,
                    _ => ApiKeyRole::User,
                };

                let request = CreateApiKeyRequest {
                    workspace_id: if first_key.workspace == "global" {
                        None
                    } else {
                        Some(Uuid::parse_str(&first_key.workspace).unwrap_or(Uuid::nil()))
                    },
                    name: first_key.name.clone(),
                    description: Some(format!("Configured via config, role: {}", first_key.role)),
                    role,
                    rate_limit: Some(first_key.rate_limit as i32),
                    expires_at: None,
                    key_secret: Some(first_key.key_secret.clone()),
                    key_id: Some(first_key.key_id.clone()),
                };

                match repo.create_api_key(&request).await {
                    Ok(key) => {
                        info!(
                            "{}",
                            t!(
                                "log.main.api_key_created_from_config",
                                key_id = key.key.key_id,
                                role = first_key.role
                            )
                        );
                    }
                    Err(e) => {
                        if !e.to_string().contains("duplicate key") {
                            warn!(
                                "{}",
                                t!("log.main.api_key_create_from_config_failed", error = e)
                            );
                        }
                    }
                }
            }
        } else {
            // No configuration, check if admin key already exists
            match repo.get_admin_api_key(Uuid::nil()).await {
                Ok(Some(admin_key)) => {
                    info!(
                        key_id = ?admin_key.key_id,
                        workspace_id = ?admin_key.workspace_id,
                        "{}",
                        t!("log.main.existing_admin_api_key_found")
                    );
                }
                Ok(None) => {
                    // Generate new admin API key
                    let admin_request = CreateApiKeyRequest {
                        workspace_id: None,
                        name: "admin".to_string(),
                        description: Some("Default Admin API Key".to_string()),
                        role: ApiKeyRole::Admin,
                        rate_limit: Some(100000),
                        expires_at: None,
                        key_secret: None,
                        key_id: None,
                    };
                    match repo.create_api_key(&admin_request).await {
                        Ok(key) => {
                            info!(
                                "{}",
                                t!(
                                    "log.main.admin_api_key_created_no_workspace",
                                    key_id = key.key.key_id
                                )
                            );

                            let is_production = nebulaid::core::config::is_production();

                            if !is_production {
                                // WARN: Print secret to console only once - user must save it
                                println!("\n╔════════════════════════════════════════════════════════════════════╗");
                                println!("║           ⚠️  ADMIN API KEY GENERATED - SAVE NOW!              ║");
                                println!("╠════════════════════════════════════════════════════════════════════╣");
                                println!(
                                    "║  Key ID: {}                                                ║",
                                    key.key.key_id
                                );
                                println!(
                                    "║  Secret: {}                                    ║",
                                    key.key_secret
                                );
                                println!("║                                                                    ║");
                                println!("║  ⚠️  THIS IS THE ONLY TIME THE SECRET WILL BE SHOWN!           ║");
                                println!("║  Save it securely - you will need it for API authentication.    ║");
                                println!("╚════════════════════════════════════════════════════════════════════╝\n");
                                tracing::warn!("{}", t!("log.main.admin_api_key_secret_printed"));
                            } else {
                                tracing::warn!(
                                    "{}",
                                    t!("log.main.admin_api_key_generated_no_print")
                                );
                            }
                        }
                        Err(e) => {
                            error!("{}", t!("log.main.admin_api_key_create_failed", error = e));
                        }
                    }
                }
                Err(e) => {
                    error!("{}", t!("log.main.admin_api_key_check_failed", error = e));
                }
            }
        }

        // Add test API key in development mode only if no configuration provided
        #[cfg(debug_assertions)]
        if admin_key_secret_from_env.is_none() && configured_keys.is_none() {
            let test_request = CreateApiKeyRequest {
                workspace_id: None,
                name: "Test Admin API Key".to_string(),
                description: Some("Default test admin API key".to_string()),
                role: ApiKeyRole::Admin,
                rate_limit: Some(10000),
                expires_at: None,
                key_secret: None,
                key_id: None,
            };
            match repo.create_api_key(&test_request).await {
                Ok(key) => {
                    info!(
                        "{}",
                        t!(
                            "log.main.test_admin_api_key_created",
                            key_id = key.key.key_id
                        )
                    );
                }
                Err(e) => {
                    if !e.to_string().contains("duplicate key") {
                        warn!("{}", t!("log.main.test_api_key_create_failed", error = e));
                    }
                }
            }
        }
    } else {
        warn!("{}", t!("log.main.no_database_connection"));
    }
}

#[cfg(feature = "etcd")]
async fn create_id_generator(
    config: &Config,
    audit_logger: Arc<AuditLogger>,
    etcd_health_monitor: Option<Arc<EtcdClusterHealthMonitor>>,
) -> Result<Arc<AlgorithmRouter>> {
    info!("{}", t!("log.main.id_generators_initializing"));

    let audit_logger_for_core: nebulaid::core::algorithm::DynAuditLogger =
        audit_logger as Arc<dyn nebulaid::core::algorithm::AuditLogger>;

    // Create CPU monitor
    let cpu_monitor = Arc::new(nebulaid::core::algorithm::CpuMonitor::new());
    // 启动 CPU 周期采样（仅 Linux：读取 /proc/stat）。任务 detached，
    // 只要进程存活即持续更新共享的 current_usage，供 Segment 动态步长使用。
    #[cfg(target_os = "linux")]
    let _cpu_sampler = cpu_monitor.start_monitoring();
    let router = AlgorithmRouter::new(config.clone(), Some(audit_logger_for_core));

    let router = router.with_cpu_monitor(cpu_monitor);
    let router = if let Some(monitor) = etcd_health_monitor {
        Arc::new(router.with_etcd_health_monitor(monitor))
    } else {
        Arc::new(router)
    };

    router.initialize().await?;

    info!("{}", t!("log.main.id_generators_initialized"));
    Ok(router)
}

#[cfg(not(feature = "etcd"))]
async fn create_id_generator(
    config: &Config,
    audit_logger: Arc<AuditLogger>,
    _etcd_health_monitor: Option<Arc<()>>,
) -> Result<Arc<AlgorithmRouter>> {
    info!(
        "{}",
        t!("log.main.id_generators_initializing_etcd_disabled")
    );

    let audit_logger_for_core: nebulaid::core::algorithm::DynAuditLogger =
        audit_logger as Arc<dyn nebulaid::core::algorithm::AuditLogger>;

    // Create CPU monitor
    let cpu_monitor = Arc::new(nebulaid::core::algorithm::CpuMonitor::new());
    // 启动 CPU 周期采样（仅 Linux：读取 /proc/stat）。任务 detached，
    // 只要进程存活即持续更新共享的 current_usage，供 Segment 动态步长使用。
    #[cfg(target_os = "linux")]
    let _cpu_sampler = cpu_monitor.start_monitoring();
    let router = AlgorithmRouter::new(config.clone(), Some(audit_logger_for_core));
    let router = router.with_cpu_monitor(cpu_monitor);
    let router = Arc::new(router);

    router.initialize().await?;

    info!("{}", t!("log.main.id_generators_initialized"));
    Ok(router)
}

async fn start_http_server(
    bind_addr: SocketAddr,
    handlers: Arc<ApiHandlers>,
    auth: Arc<ApiKeyAuth>,
    rate_limiter: Arc<RateLimiter>,
    audit_logger: Arc<AuditLogger>,
    config_service: Arc<dyn ConfigManagementService>,
    tls_manager: Option<Arc<TlsManager>>,
) -> Result<()> {
    // 限流开关来自真实配置（此前该参数被忽略，
    // `[rate_limit].enabled=false` 也照样挂限流层）。
    let rate_limit_enabled = config_service.get_config().rate_limit.enabled;
    let router = create_router_with_rate_limit(
        handlers,
        auth,
        rate_limiter,
        audit_logger,
        rate_limit_enabled,
    )
    .await
    .layer(create_size_limit_middleware())
    .merge(merge_sdforge_routes(axum::Router::new()));

    // 按配置选择明文或 TLS 监听（此前 http_acceptor 只构造
    // 不消费，HTTPS 宣称启用却恒为明文）。
    let tls_acceptor = tls_manager.as_ref().and_then(|tls| {
        if tls.is_http_enabled() {
            // 文案纠偏 —— 后 DualListener 用 TlsAcceptor 在
            // 该端口做真实 TLS 终结，不存在旧文案宣称的 "HTTP fallback"；
            // 保留旧文案会让运维误判加密端口仍是明文。
            info!("HTTPS enabled: HTTP port terminates TLS (rustls acceptor)");
            tls.http_acceptor().cloned()
        } else {
            None
        }
    });

    // 绑定地址由调用方从 config.app.http_addr() 解析传入
    info!("{}", t!("log.main.starting_http_server", addr = bind_addr));
    let listener = DualListener::bind(bind_addr, tls_acceptor).await?;

    // 注入 ConnectInfo<PeerAddr>，使限流键、认证失败计数、
    // 审计 client_ip 恢复 per-IP 语义（缺失时 get_client_ip 恒 None，全站
    // 共享单一 "anonymous" 桶——单攻击者可把 /health、/metrics 一并打成 429）。
    axum::serve(
        listener,
        router.into_make_service_with_connect_info::<PeerAddr>(),
    )
    .with_graceful_shutdown(async {
        tokio::signal::ctrl_c().await.ok();
        info!("{}", t!("log.main.shutting_down_http_server"));
    })
    .await?;

    Ok(())
}

async fn start_grpc_server(
    config: ServerConfig,
    handlers: Arc<ApiHandlers>,
    auth: Arc<ApiKeyAuth>,
    tls_manager: Option<Arc<TlsManager>>,
) -> Result<()> {
    let grpc_addr = SocketAddr::from(([0, 0, 0, 0], config.grpc_port));
    info!("{}", t!("log.main.starting_grpc_server", addr = grpc_addr));
    info!(
        "{}",
        t!("log.main.configured_grpc_port", port = config.grpc_port)
    );

    // gRPC 与 HTTP 使用同一认证器（共享 API key 仓储与失败限流）
    let grpc_server = GrpcServer::with_auth(handlers, auth);

    let shutdown = async {
        tokio::signal::ctrl_c().await.ok();
        info!("{}", t!("log.main.shutting_down_grpc_server"));
    };

    let mut server_builder = Server::builder();

    if let Some(ref tls) = tls_manager {
        if tls.is_grpc_enabled() {
            info!("{}", t!("log.main.grpc_tls_enabled"));
            if let Some(grpc_tls_config) = tls.grpc_tls_config() {
                let config = grpc_tls_config.as_ref().clone();
                server_builder = server_builder.tls_config(config).map_err(|e| {
                    nebulaid::core::types::CoreError::InternalError(format!(
                        "TLS config error: {}",
                        e
                    ))
                })?;
            }
        }
    }

    server_builder
        .add_service(NebulaIdServiceServer::new(grpc_server))
        .serve_with_shutdown(grpc_addr, shutdown)
        .await
        .map_err(|e| {
            nebulaid::core::types::CoreError::InternalError(format!("gRPC server error: {}", e))
        })?;

    Ok(())
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("Failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("Failed to install signal handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        _ = ctrl_c => {},
        _ = terminate => {},
    }
}

/// 抽取 etcd / non-etcd 分支共用的 ApiHandlers 构造逻辑。
///
/// 原代码在两个 cfg 分支重复调用 `ApiHandlers::with_api_key_repository`
/// + `.with_key_rotation_grace_period`，未来新增 builder 方法需同步改两处
/// （霰弹手术气味）。本 helper 集中构造逻辑。
#[allow(clippy::too_many_arguments, clippy::doc_lazy_continuation)]
fn build_api_handlers(
    id_generator: Arc<nebulaid::core::algorithm::AlgorithmRouter>,
    cs: Arc<dyn ConfigManagementService>,
    repo: Arc<dyn ApiKeyRepository>,
    grace_period_seconds: u64,
) -> ApiHandlers {
    ApiHandlers::with_api_key_repository(id_generator, cs, repo)
        .with_key_rotation_grace_period(grace_period_seconds)
}

/// T008 —— 生产环境强制 TLS 的判定核心（纯判定 + 一处逃生门 warn，便于单测）。
///
/// 规则（fail-fast）：
/// - 非 production，或 `tls.enabled == true` → 放行；
/// - production 且 TLS 关闭时：
///   - `allow_insecure_tls == Some("1")`（即 `NEBULA_ALLOW_INSECURE_TLS=1`）→
///     放行并 warn（仅限内网评估的显式豁免）；
///   - 其余情形 → `Err`，调用方打印本地化 error 并以非零码退出。
///
/// production 判定含 T007 反向默认：`NEBULA_ENV` 缺失/未知值按生产执行，
/// 因此缺省部署同样被本校验覆盖。
fn validate_tls_required_in_production(
    environment: Environment,
    tls_enabled: bool,
    allow_insecure_tls: Option<&str>,
) -> Result<()> {
    if !environment.is_production() || tls_enabled {
        return Ok(());
    }
    if allow_insecure_tls == Some("1") {
        warn!("{}", t!("log.main.tls_insecure_escape_hatch_active"));
        return Ok(());
    }
    Err(nebulaid::core::types::CoreError::ConfigurationError(
        "TLS is required in production but tls.enabled = false".to_string(),
    ))
}

/// T016 —— etcd 协调组件装配产物（仅 etcd feature）。
///
/// `lock` 供仓储号段分配跨进程互斥；`client` 为共享长连接 etcd 客户端，
/// 供 T017 worker 分配与 T027 健康巡检注入复用；`None` = 未配置 etcd 的单机模式。
#[cfg(feature = "etcd")]
struct CoordinationComponents {
    lock: std::sync::Arc<dyn nebulaid::core::coordinator::DistributedLock + Send + Sync>,
    /// 共享长连接 etcd client（T017 worker 分配 / T027 健康巡检注入复用）；
    /// `None` = 未配置 etcd 的单机模式。
    client: Option<std::sync::Arc<dyn nebulaid::core::coordinator::EtcdClientOps>>,
}

/// T017 —— worker 租约守护（仅 etcd feature）：持有分配器与 keepalive 停机通道。
///
/// 续期连续失败的致命错误经独立的 oneshot 通道（`allocate_worker_id` 的
/// `failure_tx` 入参）上报，main 的 select 接入后触发优雅停机（fail-stop）；
/// `stop_tx` 用于正常停机时让 keepalive 任务退出。
#[cfg(feature = "etcd")]
struct WorkerLeaseGuard {
    allocator: std::sync::Arc<nebulaid::core::coordinator::EtcdWorkerAllocator>,
    worker_id: u16,
    stop_tx: tokio::sync::watch::Sender<bool>,
}

/// T017 —— worker_id 运行时分配（Snowflake 构造前调用）。
///
/// 经 `EtcdWorkerAllocator::allocate()` 从 etcd 抢占 worker key（key value =
/// 本实例 instance_id，lease 30s 绑定存活），成功后 spawn lease keepalive
/// 任务（interval = lease_ttl/3）。任一步失败返回 `Err`，调用方拒绝启动 ——
/// 多实例部署回退静态默认 0 必然产生重复 worker_id（数据正确性事故）。
#[cfg(feature = "etcd")]
async fn allocate_worker_id(
    client: std::sync::Arc<dyn nebulaid::core::coordinator::EtcdClientOps>,
    config: &Config,
    failure_tx: tokio::sync::oneshot::Sender<String>,
) -> Result<WorkerLeaseGuard> {
    use nebulaid::core::coordinator::EtcdWorkerAllocator;

    let allocator = EtcdWorkerAllocator::new(client.clone(), config.app.dc_id, config.etcd.clone())
        .await
        .map_err(|e| {
            nebulaid::core::types::CoreError::ConfigurationError(format!(
                "etcd worker allocator init failed: {}",
                e
            ))
        })?;
    let worker_id = allocator.allocate().await.map_err(|e| {
        nebulaid::core::types::CoreError::ConfigurationError(format!(
            "etcd worker_id allocation failed: {}",
            e
        ))
    })?;
    if worker_id > u8::MAX as u16 {
        return Err(nebulaid::core::types::CoreError::ConfigurationError(
            format!(
                "etcd allocated worker_id {} exceeds config.worker_id u8 range",
                worker_id
            ),
        ));
    }

    let lease_id = allocator.current_lease_id();
    let allocator = std::sync::Arc::new(allocator);
    let (stop_tx, stop_rx) = tokio::sync::watch::channel(false);
    tokio::spawn(EtcdWorkerAllocator::run_lease_keepalive_loop(
        client,
        lease_id,
        EtcdWorkerAllocator::keepalive_interval(),
        EtcdWorkerAllocator::KEEPALIVE_MAX_CONSECUTIVE_FAILURES,
        stop_rx,
        failure_tx,
    ));
    info!(
        "{}",
        t!(
            "log.main.worker_id_allocated_from_etcd",
            worker_id = worker_id,
            lease_id = lease_id
        )
    );
    Ok(WorkerLeaseGuard {
        allocator,
        worker_id,
        stop_tx,
    })
}

/// T016 —— etcd 协调组件装配（fail-closed）。
///
/// 规则：
/// - 未配置 etcd endpoints → 单机部署合法，返回 `LocalDistributedLock`
///   （`client` 为 `None`），不拒绝启动；
/// - 配置了 endpoints → 建立长连接 client 并 ping 探活（`etcd_client::Client`
///   的 connect 是 lazy 的，构造成功不代表可达），再构造 `EtcdDistributedLock`；
///   任一步失败返回 `Err`，调用方打印本地化 error 并以非零码退出 —— 多实例
///   部署静默回退进程内锁必然产生重复 ID（数据正确性事故），禁止降级。
#[cfg(feature = "etcd")]
async fn assemble_coordination(config: &Config) -> Result<CoordinationComponents> {
    use nebulaid::core::coordinator::{
        EtcdClientWrapper, EtcdDistributedLock, LocalDistributedLock, SEGMENT_LOCK_PATH_PREFIX,
    };

    if config.etcd.endpoints.is_empty() {
        warn!("Etcd endpoints not configured, using LocalDistributedLock (single-process only)");
        return Ok(CoordinationComponents {
            lock: std::sync::Arc::new(LocalDistributedLock::new()),
            client: None,
        });
    }

    // fail-closed：配置显式含 etcd endpoints，装配任一步失败 → Err（拒绝启动）。
    let wrapper = EtcdClientWrapper::new(config.etcd.endpoints.clone())
        .await
        .map_err(|e| {
            nebulaid::core::types::CoreError::ConfigurationError(format!(
                "etcd client connect failed for endpoints {:?}: {}",
                config.etcd.endpoints, e
            ))
        })?;
    let client: std::sync::Arc<dyn nebulaid::core::coordinator::EtcdClientOps> =
        std::sync::Arc::new(wrapper);

    // lazy connect 探活：ping 不通 = etcd 实际不可用，与连接失败同口径 fail-closed。
    let probe_timeout = std::time::Duration::from_millis(config.etcd.connect_timeout_ms.max(1));
    match tokio::time::timeout(probe_timeout, client.ping()).await {
        Ok(Ok(())) => {}
        Ok(Err(e)) => {
            return Err(nebulaid::core::types::CoreError::ConfigurationError(format!(
                "etcd ping failed for endpoints {:?}: {}",
                config.etcd.endpoints, e
            )));
        }
        Err(_) => {
            return Err(nebulaid::core::types::CoreError::ConfigurationError(format!(
                "etcd ping timed out after {}ms for endpoints {:?}",
                config.etcd.connect_timeout_ms, config.etcd.endpoints
            )));
        }
    }

    let etcd_lock =
        EtcdDistributedLock::new(client.clone(), SEGMENT_LOCK_PATH_PREFIX.to_string())
            .await
            .map_err(|e| {
                nebulaid::core::types::CoreError::ConfigurationError(format!(
                    "failed to create EtcdDistributedLock: {}",
                    e
                ))
            })?;

    Ok(CoordinationComponents {
        lock: std::sync::Arc::new(etcd_lock),
        client: Some(client),
    })
}

/// T018 —— 无 etcd 路径默认 worker 标识风险判定（纯判定，便于单测）。
///
/// 未配置 etcd（无运行时 worker 分配）且 worker_id / dc_id 任一仍为默认值 0
/// 时返回 true：此时 Snowflake 直接以配置值作为机器标识，多实例部署若不显式
/// 配置 `WORKER_ID` / `DC_ID`（或写进配置文件），两实例拿到同一 (dc_id,
/// worker_id) 组合必然产生重复 ID。仅告警不拦截 —— 单实例部署取默认值合法。
fn should_warn_default_worker_identity(
    etcd_endpoints_configured: bool,
    worker_id: u8,
    dc_id: u8,
) -> bool {
    !etcd_endpoints_configured && (worker_id == 0 || dc_id == 0)
}

#[tokio::main]
async fn main() -> Result<()> {
    // 日志初始化由 inklog 接管（替换原手写的 tracing_subscriber::fmt() 链）。
    // 本地 ../inklog 已切换至 EnvFilter，自动从 RUST_LOG 读取按模块过滤规则
    // （如 `RUST_LOG=nebulaid=debug,hyper=warn`），无需手动读取环境变量。
    // format 是渲染模板（inklog 0.3 语义，非旧命名格式）；JSON 行输出由
    // console_json 开启。Arc 持有实例：热重载回调需借同一实例热调全局
    // 级别（set_level 经内部 reload 句柄作用于 live subscriber）。
    let logger = Arc::new(
        inklog::LoggerManager::builder()
            .level("info")
            .format("{timestamp} [{level}] {target} - {message}")
            .console_json(true)
            .build()
            .await?,
    );

    // Phase 8 ICU i18n — initialize default locale before any t!() lookup.
    nebulaid::core::i18n::init_i18n("en");

    info!("{}", t!("log.main.starting_service"));
    info!(
        "{}",
        t!("log.main.version", version = env!("CARGO_PKG_VERSION"))
    );

    // Initialize sdforge plugins so inventory-registered routes are linked
    // into the final binary (prevents linker stripping). Must be called
    // before merge_sdforge_routes builds the axum Router.
    let plugin_counts = init_sdforge();
    info!(
        routes = plugin_counts.routes,
        "{}",
        t!("log.main.sdforge_plugins_initialized")
    );

    // Parse command line arguments
    let args: Vec<String> = env::args().collect();
    let explicit_path = args.len() > 2 && args[1] == "--config";
    let config_path = if explicit_path {
        args[2].clone()
    } else {
        DEFAULT_CONFIG_PATH.to_string()
    };

    info!("{}", t!("log.main.loading_config", path = config_path));

    // Load config from file first, then merge with environment variables
    //
    // 加载失败不再降级为 `Config::default()`。原实现把错误 `error!` 一行
    // 后继续启动，等价于用一套没人审阅过的默认配置对外提供服务；坏配置现在直接让
    // 进程以非零码退出，消息里带上路径与原因。只有"未显式指定 --config 且该路径确实
    // 不存在"才允许回落内置默认值，且必须显式 warn。
    let (mut config, source) =
        resolve_startup_config(&config_path, explicit_path).map_err(|e| {
            nebulaid::core::types::CoreError::ConfigurationError(format!(
                "failed to load configuration from '{}': {}",
                config_path, e
            ))
        })?;
    if matches!(source, StartupConfig::DefaultsBecauseMissing) {
        warn!(
            "{}",
            t!(
                "log.main.config_defaults_because_missing",
                path = config_path
            )
        );
    }

    // Apply environment variable overrides
    config.merge(Config::load_from_env().map_err(|e| {
        nebulaid::core::types::CoreError::ConfigurationError(format!(
            "failed to load configuration from environment: {}",
            e
        ))
    })?);
    info!("{}", t!("log.main.config_loaded"));

    // T018 —— 无 etcd 时默认 worker 标识多实例风险告警：etcd 未配置意味着
    // 没有 worker_id 运行时分配兜底，worker_id/dc_id 任一为默认 0 时显性
    // 提醒（多实例必须显式配置，否则 Snowflake 会重复）。
    if should_warn_default_worker_identity(
        !config.etcd.endpoints.is_empty(),
        config.app.worker_id,
        config.app.dc_id,
    ) {
        warn!(
            "{}",
            t!(
                "log.main.default_worker_id_warning",
                worker_id = config.app.worker_id,
                dc_id = config.app.dc_id
            )
        );
    }

    // T008 —— 生产环境强制 TLS（fail-fast）。环境判定经 Environment::from_env()
    //（含 T007 反向默认：NEBULA_ENV 缺失/未知值按生产执行，缺失时此处顺带
    // 触发唯一一次 warn）。校验失败打印本地化 error 并以非零码退出；
    // NEBULA_ALLOW_INSECURE_TLS=1 显式放行（函数内 warn）。
    if validate_tls_required_in_production(
        Environment::from_env(),
        config.tls.enabled,
        env::var("NEBULA_ALLOW_INSECURE_TLS").ok().as_deref(),
    )
    .is_err()
    {
        error!("{}", t!("error.main.tls_required_in_production"));
        error!("{}", t!("log.main.shutting_down"));
        std::process::exit(1);
    }

    let server_config = ServerConfig {
        http_port: config.app.http_port,
        grpc_port: config.app.grpc_port,
        workers: std::thread::available_parallelism()
            .map(|p| p.get())
            .unwrap_or(1),
        shutdown_timeout_secs: config.app.shutdown_timeout_seconds,
    };

    // HTTP 绑定地址唯一来源于 config.app（host + http_port），修复原先
    // 忽略配置、硬编码 [0,0,0,0]:8080 导致 http_port 配置失效的缺陷。
    let http_bind_addr: SocketAddr = config.app.http_addr().map_err(|e| {
        nebulaid::core::types::CoreError::InternalError(format!(
            "invalid http bind address from config.app (host={}, port={}): {}",
            config.app.host, config.app.http_port, e
        ))
    })?;

    info!(
        "{}",
        t!(
            "log.main.starting_server_on_ports",
            http_port = server_config.http_port,
            grpc_port = server_config.grpc_port
        )
    );

    // Initialize database connection first (needed for API key auth)
    info!("{}", t!("log.main.connecting_to_database"));
    let db_connection = match database::create_connection(&config.database).await {
        Ok(conn) => {
            info!("{}", t!("log.main.database_connected"));

            // Run auto migrations to create tables
            if let Err(e) = database::run_migrations(&conn).await {
                error!("{}", t!("log.main.migrations_failed", error = e));
                error!("{}", t!("log.main.shutting_down"));
                std::process::exit(1);
            }

            Some(conn)
        }
        Err(e) => {
            error!("{}", t!("log.main.database_connect_failed", error = e));
            error!("{}", t!("log.main.check_database_url"));
            error!("{}", t!("log.main.shutting_down"));
            std::process::exit(1);
        }
    };

    // T016 —— 分布式锁装配（fail-closed），提前到仓储构造之前：
    // 配置显式含 etcd endpoints 时，etcd 不可用直接拒绝启动（多实例场景
    // 静默回退进程内锁必然重复 ID）；未配置 endpoints 才允许单机本地锁。
    #[cfg(not(feature = "etcd"))]
    let lock: std::sync::Arc<dyn nebulaid::core::coordinator::DistributedLock + Send + Sync> =
        std::sync::Arc::new(nebulaid::core::coordinator::LocalDistributedLock::new());
    #[cfg(feature = "etcd")]
    let coordination = match assemble_coordination(&config).await {
        Ok(components) => components,
        Err(e) => {
            error!(
                "{}",
                t!("error.main.etcd_required_but_unavailable", error = e)
            );
            error!("{}", t!("log.main.shutting_down"));
            std::process::exit(1);
        }
    };
    #[cfg(feature = "etcd")]
    let lock: std::sync::Arc<dyn nebulaid::core::coordinator::DistributedLock + Send + Sync> =
        coordination.lock.clone();

    let repository: Option<Arc<database::SeaOrmRepository>> = if let Some(conn) = db_connection {
        // tiangang C1 修复：生产环境强制校验 api_key_salt 非空且非弱默认值。
        // 规则 12（失败必须显性化）：校验失败时 panic，禁止弱 pepper 静默放行。
        if nebulaid::core::config::is_production() {
            let salt = &config.auth.api_key_salt;
            if salt.is_empty()
                || salt.len() < 16
                || salt == "test"
                || salt == "test-secret-value-12345"
            {
                panic!(
                    "{}",
                    t!(
                        "error.main.invalid_api_key_salt_production",
                        env = "NEBULA_API_KEY_SALT"
                    )
                );
            }
        }

        let repo = Arc::new(
            database::SeaOrmRepository::new(conn, config.auth.api_key_salt.clone())
                .with_distributed_lock(lock),
        );
        info!("{}", t!("log.main.database_repository_initialized"));
        Some(repo)
    } else {
        None
    };

    info!(
        "{}",
        t!("log.main.auth_enabled", enabled = config.auth.enabled)
    );

    // 认证决策缓存 —— ApiKeyAuth 与 ApiHandlers
    // 共享同一实例：前者读缓存加速校验，后者在吊销/轮换/重置时失效条目。
    // `cache_ttl_seconds = 0` 表示禁用，此时不再装配实例（装配了也不会写入，
    // 却仍要在每次校验后多打一次 get_api_key_by_id 判因，纯空转开销）。
    #[cfg(feature = "garrison-auth")]
    let auth_cache: Option<Arc<nebulaid::server::auth::AuthCache>> =
        match (repository.as_ref(), config.auth.cache_ttl_seconds) {
            (Some(_), ttl @ 1..) => {
                info!(
                    ttl_seconds = ttl,
                    "auth decision cache enabled (in-process GarrisonDao impl)"
                );
                Some(Arc::new(nebulaid::server::auth::AuthCache::new(ttl).await))
            }
            (Some(_), 0) => {
                info!("auth decision cache disabled (auth.cache_ttl_seconds = 0)");
                None
            }
            (None, _) => None,
        };

    // Create API key auth with repository for database-backed storage
    // Phase 9 — configure trusted proxies so the auth
    // middleware only honors `X-Forwarded-For` / `X-Real-IP` when the
    // direct peer IP is in `NEBULA_TRUSTED_PROXIES`. Default: empty
    // (no headers trusted, all clients identified by TCP peer IP).
    let trusted_proxies: Vec<std::net::IpAddr> = std::env::var("NEBULA_TRUSTED_PROXIES")
        .ok()
        .map(|s| s.split(',').filter_map(|p| p.trim().parse().ok()).collect())
        .unwrap_or_default();
    let auth: Arc<ApiKeyAuth> = if let Some(ref repo) = repository {
        #[cfg_attr(not(feature = "garrison-auth"), allow(unused_mut))]
        let mut auth_builder = ApiKeyAuth::new(repo.clone(), config.auth.enabled)
            .with_trusted_proxies(trusted_proxies.clone());
        #[cfg(feature = "garrison-auth")]
        if let Some(cache) = auth_cache.clone() {
            auth_builder = auth_builder.with_cache(cache);
        }
        Arc::new(auth_builder)
    } else {
        error!("{}", t!("log.main.fatal_api_key_auth_requires_database"));
        std::process::exit(1);
    };
    let _ = trusted_proxies; // also consumed by router.rs via env var
    load_api_keys(&auth, &repository, &config).await;

    // Initialize audit logger and config (used by both etcd and non-etcd modes)
    let audit_logger = Arc::new(AuditLogger::new(config.rate_limit.default_rps as usize));
    let hot_config = Arc::new(HotReloadConfig::new(
        config.clone(),
        "config/config.toml".to_string(),
    ));

    // inklog set_level 热调：热重载/管理端改 logging.level 时同步热调全局
    // subscriber（此前仅更新 hot config 快照，级别变更不生效，需重启进程）。
    {
        let logger = Arc::clone(&logger);
        hot_config.add_reload_callback(move |cfg| {
            let level = cfg.logging.level.to_string();
            if let Err(e) = logger.set_level(None, &level) {
                tracing::error!(error = ?e, level = %level, "inklog set_level hot-apply failed");
            }
        });
    }

    // hot_reload 文件监视启动条件与 feature / repo 解耦 ——
    // 仅取决于 `hot_reload.auto_watch_enabled`，etcd 与非 etcd 分支共用。
    // （原实现位于 etcd 分支"无 repo"路径，非 etcd 构建从不启动监视。）
    if config.hot_reload.auto_watch_enabled {
        let watcher = hot_config.clone();
        tokio::spawn(async move {
            watcher.watch(2000).await;
        });
        info!("{}", t!("log.main.hot_reload_watcher_started"));
    }

    #[cfg(feature = "etcd")]
    {
        info!("{}", t!("log.main.initializing_etcd_health_monitor"));
        let etcd_cache_path = format!("./data/etcd_cache_{}.json", config.app.dc_id);

        // F-01 修复：生产路径注入 EtcdClientWrapper，让 check_etcd_health 走 trait 抽象层。
        // 尝试建立长连接 client；失败则回退到 new()（每次检查新建 client 的 fallback 路径）。
        let etcd_health_monitor = if !config.etcd.endpoints.is_empty() {
            match EtcdClientWrapper::new(config.etcd.endpoints.clone()).await {
                Ok(client) => {
                    info!("{}", t!("log.main.etcd_client_wrapper_initialized"));
                    Arc::new(EtcdClusterHealthMonitor::new_with_client(
                        config.etcd.clone(),
                        etcd_cache_path,
                        Arc::new(client),
                    ))
                }
                Err(e) => {
                    warn!(
                        "{}",
                        t!("log.main.etcd_client_wrapper_init_failed", error = e)
                    );
                    Arc::new(EtcdClusterHealthMonitor::new(
                        config.etcd.clone(),
                        etcd_cache_path,
                    ))
                }
            }
        } else {
            Arc::new(EtcdClusterHealthMonitor::new(
                config.etcd.clone(),
                etcd_cache_path,
            ))
        };

        if let Err(e) = etcd_health_monitor.load_local_cache().await {
            warn!("{}", t!("log.main.etcd_local_cache_load_failed", error = e));
        }

        info!("{}", t!("log.main.etcd_health_monitor_initialized"));

        // T017 —— worker_id 运行时分配：etcd 已配置（coordination.client 为
        // Some）时于 Snowflake 构造前分配并覆盖静态配置值；分配失败 fail-closed
        // （多实例回退静态默认 0 必然重复 ID）。
        let (lease_failure_tx, lease_failure_rx) = tokio::sync::oneshot::channel::<String>();
        let worker_lease: Option<WorkerLeaseGuard> = match &coordination.client {
            Some(client) => {
                match allocate_worker_id(client.clone(), &config, lease_failure_tx).await {
                    Ok(guard) => Some(guard),
                    Err(e) => {
                        error!("{}", t!("error.main.worker_id_allocation_failed", error = e));
                        error!("{}", t!("log.main.shutting_down"));
                        std::process::exit(1);
                    }
                }
            }
            None => None,
        };
        if let Some(guard) = &worker_lease {
            // 分配器 MAX_WORKER_ID=255，覆盖值必在 config.worker_id 的 u8 值域内
            config.app.worker_id = guard.worker_id as u8;
        }

        let id_generator = create_id_generator(
            &config,
            audit_logger.clone(),
            Some(etcd_health_monitor.clone()),
        )
        .await?;

        // 限流器先于 ConfigManager 创建，经 with_rate_limiter
        // 共享给运行时配置服务，使 POST /config/rate-limit 热更新作用于流量。
        let rate_limiter = Arc::new(RateLimiter::new(
            config.rate_limit.default_rps,
            config.rate_limit.burst_size,
        ));
        // 启动限流桶清理后台任务（5 分钟空闲桶回收，60s 周期），
        // 停机时经 abort 退出，防止任务泄漏。
        let rate_limit_cleanup = rate_limiter.start_cleanup(
            std::time::Duration::from_secs(300),
            std::time::Duration::from_secs(60),
        );

        let (handlers, config_service) = if let Some(ref repo) = repository {
            let cs = Arc::new(
                ConfigManager::with_repository(
                    hot_config.clone(),
                    id_generator.clone(),
                    repo.clone(),
                    repo.clone(),
                    repo.clone(),
                )
                .with_rate_limiter(rate_limiter.clone()),
            );
            let h = build_api_handlers(
                id_generator.clone(),
                cs.clone(),
                repo.clone(),
                config.auth.key_rotation_grace_period_seconds,
            );
            #[cfg(feature = "garrison-auth")]
            let h = if let Some(cache) = auth_cache.clone() {
                h.with_auth_cache(cache)
            } else {
                h
            };
            let h = Arc::new(h);
            (h, cs)
        } else {
            let cs = Arc::new(
                ConfigManager::new(hot_config.clone(), id_generator.clone())
                    .with_rate_limiter(rate_limiter.clone()),
            );
            // hot_reload 监视已移至两分支公共位置，此处不再重复启动。
            let h = Arc::new(ApiHandlers::new(id_generator.clone(), cs.clone()));
            (h, cs)
        };

        // TLS 配置错误 fail-fast —— enabled=true 且证书缺失/
        // 解析失败时拒绝启动（不再静默降级明文）。enabled=false 时
        // initialize() 直接返回 Ok，明文部署不受影响。
        let mut tls_manager = TlsManager::new(config.tls.clone());
        tls_manager.initialize().await.map_err(|e| {
            error!("{}", t!("log.main.tls_init_failed", error = e));
            nebulaid::core::types::CoreError::InternalError(format!(
                "TLS configuration error: {}",
                e
            ))
        })?;
        let tls_manager = if tls_manager.is_http_enabled() || tls_manager.is_grpc_enabled() {
            Some(Arc::new(tls_manager))
        } else {
            None
        };

        info!("{}", t!("log.main.starting_degradation_check"));
        let degradation_manager = id_generator.get_degradation_manager();
        degradation_manager.start_background_check();

        info!("{}", t!("log.main.server_initialized_starting"));

        let http_server = tokio::spawn(start_http_server(
            http_bind_addr,
            handlers.clone(),
            auth.clone(),
            rate_limiter.clone(),
            audit_logger.clone(),
            config_service.clone(),
            tls_manager.clone(),
        ));
        let grpc_server = tokio::spawn(start_grpc_server(
            server_config,
            handlers,
            auth.clone(),
            tls_manager,
        ));

        // http / grpc / 停机信号任一路径先就绪时，统一在 select 之后回收
        // 后台任务（降级巡检 + 限流桶清理）再返回。原实现只在 shutdown_signal
        // 分支 abort：服务器先退出（正常停止或错误退出）时清理任务泄漏，
        // tokio 运行时 drop 还会一直等这个永不自退的循环任务。
        let server_result: Result<()> = tokio::select! {
            http_result = http_server => match http_result {
                Ok(Ok(())) => {
                    info!("{}", t!("log.main.http_server_stopped"));
                    Ok(())
                }
                Ok(Err(e)) => {
                    error!("{}", t!("log.main.http_server_error", error = e));
                    Err(e)
                }
                Err(e) => {
                    error!("{}", t!("log.main.http_server_panic", error = e));
                    Err(nebulaid::core::types::CoreError::InternalError(format!("HTTP server panic: {}", e)))
                }
            },
            grpc_result = grpc_server => match grpc_result {
                Ok(Ok(())) => {
                    info!("{}", t!("log.main.grpc_server_stopped"));
                    Ok(())
                }
                Ok(Err(e)) => {
                    error!("{}", t!("log.main.grpc_server_error", error = e));
                    Err(e)
                }
                Err(e) => {
                    error!("{}", t!("log.main.grpc_server_panic", error = e));
                    Err(nebulaid::core::types::CoreError::InternalError(format!("gRPC server panic: {}", e)))
                }
            },
            _ = shutdown_signal() => {
                info!("{}", t!("log.main.shutdown_signal_received"));
                Ok(())
            }
            // T017 —— lease 续期连续失败 fail-stop：etcd 不可达使 lease 失效后，
            // 该 worker_id 可能已被其他实例接管，继续发号会重复 ID → 触发优雅停机。
            // 未配置 etcd（worker_lease 为 None）时该臂永不触发。
            lease_reason = async {
                if worker_lease.is_some() {
                    lease_failure_rx
                        .await
                        .unwrap_or_else(|_| "lease keepalive task dropped".to_string())
                } else {
                    std::future::pending::<String>().await
                }
            } => {
                error!(
                    "{}",
                    t!("error.main.worker_lease_renewal_failed", reason = lease_reason)
                );
                error!("{}", t!("log.main.shutting_down"));
                Err(nebulaid::core::types::CoreError::InternalError(format!(
                    "worker lease renewal failed: {}",
                    lease_reason
                )))
            }
        };

        degradation_manager.stop_background_check().await;
        rate_limit_cleanup.abort();

        // T017 —— 停机收尾：停 keepalive 任务，并经归属校验释放 worker_id
        //（best-effort：失败仅告警，lease TTL 到期后 etcd 会自动回收 key）。
        if let Some(guard) = &worker_lease {
            let _ = guard.stop_tx.send(true);
            if let Err(e) = guard.allocator.release(guard.worker_id).await {
                warn!(
                    "{}",
                    t!(
                        "log.main.worker_id_release_on_shutdown_failed",
                        worker_id = guard.worker_id,
                        error = e
                    )
                );
            } else {
                info!(
                    "{}",
                    t!(
                        "log.main.worker_id_released_on_shutdown",
                        worker_id = guard.worker_id
                    )
                );
            }
        }

        server_result
    }

    #[cfg(not(feature = "etcd"))]
    {
        info!("{}", t!("log.main.etcd_disabled"));

        // 删除原此处创建后即丢弃的 AlgorithmRouter 死代码；
        // id_generator 由 create_id_generator 构建并作为实际生成器使用。
        let id_generator = create_id_generator(&config, audit_logger.clone(), None).await?;

        // 限流器先于 ConfigManager 创建并共享（同 etcd 分支）
        let rate_limiter = Arc::new(RateLimiter::new(
            config.rate_limit.default_rps,
            config.rate_limit.burst_size,
        ));
        // 启动限流桶清理后台任务（5 分钟空闲桶回收，60s 周期），
        // 停机时经 abort 退出，防止任务泄漏。
        let rate_limit_cleanup = rate_limiter.start_cleanup(
            std::time::Duration::from_secs(300),
            std::time::Duration::from_secs(60),
        );

        let (handlers, config_service) = if let Some(ref repo) = repository {
            let cs = Arc::new(
                ConfigManager::with_repository(
                    hot_config,
                    id_generator.clone(),
                    repo.clone(),
                    repo.clone(),
                    repo.clone(),
                )
                .with_rate_limiter(rate_limiter.clone()),
            );
            let h = build_api_handlers(
                id_generator.clone(),
                cs.clone(),
                repo.clone(),
                config.auth.key_rotation_grace_period_seconds,
            );
            #[cfg(feature = "garrison-auth")]
            let h = if let Some(cache) = auth_cache.clone() {
                h.with_auth_cache(cache)
            } else {
                h
            };
            let h = Arc::new(h);
            (h, cs)
        } else {
            let cs = Arc::new(
                ConfigManager::new(hot_config, id_generator.clone())
                    .with_rate_limiter(rate_limiter.clone()),
            );
            let h = Arc::new(ApiHandlers::new(id_generator.clone(), cs.clone()));
            (h, cs)
        };

        // TLS 配置错误 fail-fast —— enabled=true 且证书缺失/
        // 解析失败时拒绝启动（不再静默降级明文）。enabled=false 时
        // initialize() 直接返回 Ok，明文部署不受影响。
        let mut tls_manager = TlsManager::new(config.tls.clone());
        tls_manager.initialize().await.map_err(|e| {
            error!("{}", t!("log.main.tls_init_failed", error = e));
            nebulaid::core::types::CoreError::InternalError(format!(
                "TLS configuration error: {}",
                e
            ))
        })?;
        let tls_manager = if tls_manager.is_http_enabled() || tls_manager.is_grpc_enabled() {
            Some(Arc::new(tls_manager))
        } else {
            None
        };

        info!("{}", t!("log.main.starting_degradation_check"));
        let degradation_manager = id_generator.get_degradation_manager();
        degradation_manager.start_background_check();

        info!("{}", t!("log.main.server_initialized_starting"));

        let http_server = tokio::spawn(start_http_server(
            http_bind_addr,
            handlers.clone(),
            auth.clone(),
            rate_limiter.clone(),
            audit_logger.clone(),
            config_service.clone(),
            tls_manager.clone(),
        ));
        let grpc_server = tokio::spawn(start_grpc_server(
            server_config,
            handlers,
            auth.clone(),
            tls_manager,
        ));

        // http / grpc / 停机信号任一路径先就绪时，统一在 select 之后回收
        // 后台任务（降级巡检 + 限流桶清理）再返回。原实现只在 shutdown_signal
        // 分支 abort：服务器先退出（正常停止或错误退出）时清理任务泄漏，
        // tokio 运行时 drop 还会一直等这个永不自退的循环任务。
        let server_result: Result<()> = tokio::select! {
            http_result = http_server => match http_result {
                Ok(Ok(())) => {
                    info!("{}", t!("log.main.http_server_stopped"));
                    Ok(())
                }
                Ok(Err(e)) => {
                    error!("{}", t!("log.main.http_server_error", error = e));
                    Err(e)
                }
                Err(e) => {
                    error!("{}", t!("log.main.http_server_panic", error = e));
                    Err(nebulaid::core::types::CoreError::InternalError(format!("HTTP server panic: {}", e)))
                }
            },
            grpc_result = grpc_server => match grpc_result {
                Ok(Ok(())) => {
                    info!("{}", t!("log.main.grpc_server_stopped"));
                    Ok(())
                }
                Ok(Err(e)) => {
                    error!("{}", t!("log.main.grpc_server_error", error = e));
                    Err(e)
                }
                Err(e) => {
                    error!("{}", t!("log.main.grpc_server_panic", error = e));
                    Err(nebulaid::core::types::CoreError::InternalError(format!("gRPC server panic: {}", e)))
                }
            },
            _ = shutdown_signal() => {
                info!("{}", t!("log.main.shutdown_signal_received"));
                Ok(())
            }
        };

        degradation_manager.stop_background_check().await;
        rate_limit_cleanup.abort();

        server_result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nebulaid::core::algorithm::AlgorithmRouter;
    use nebulaid::core::config::Config;
    use nebulaid::server::config::hot_reload::HotReloadConfig;
    use std::sync::Arc;

    /// Setup test environment - must be called at the start of each test
    fn setup_test_env() {
        std::env::set_var("NEBULA_DATABASE_PASSWORD", "test_password");
    }

    #[tokio::test]
    async fn test_server_config_default() {
        let config = ServerConfig::default();
        // 端口默认值唯一归属 AppConfig::default（删除本地端口常量后）
        let app = nebulaid::core::config::AppConfig::default();
        assert_eq!(config.http_port, app.http_port);
        assert_eq!(config.grpc_port, app.grpc_port);
        assert!(config.workers > 0);
        assert_eq!(config.shutdown_timeout_secs, 30);
    }

    #[tokio::test]
    async fn test_create_router_with_handlers() {
        setup_test_env();
        use async_trait::async_trait;

        #[derive(Clone)]
        struct MockApiKeyRepo;

        #[async_trait]
        impl database::ApiKeyRepository for MockApiKeyRepo {
            async fn create_api_key(
                &self,
                _request: &database::CreateApiKeyRequest,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_secret".to_string(),
                    grace_expires_at: None,
                })
            }

            async fn get_api_key_by_id(
                &self,
                _key_id: &str,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn validate_api_key(
                &self,
                _key_id: &str,
                _key_secret: &str,
            ) -> nebulaid::core::types::Result<Option<database::AuthenticatedKey>> {
                Ok(None)
            }

            async fn list_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
                _limit: Option<u32>,
                _offset: Option<u32>,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }

            async fn delete_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn revoke_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn update_last_used(
                &self,
                _key: uuid::Uuid,
            ) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn get_admin_api_key(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn count_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            /// admin 守卫用：本 mock 只做 bin 装配，与 get_api_key_by_id 一样返回 None。
            async fn find_api_key_by_row_id(
                &self,
                _id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            /// admin 守卫用：本 mock 只做 bin 装配，与 count_api_keys 一样返回 0。
            async fn count_admin_keys(&self) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            async fn rotate_api_key(
                &self,
                _key_id: &str,
                _grace_period_seconds: u64,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_rotated_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Rotated Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_rotated_secret".to_string(),
                    grace_expires_at: None,
                })
            }

            async fn get_keys_older_than(
                &self,
                _age_threshold_days: i64,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }
        }

        let config = Config::default();
        let audit_logger: Arc<dyn nebulaid::core::algorithm::AuditLogger> =
            Arc::new(AuditLogger::new(10000));
        let router = AlgorithmRouter::new(config.clone(), Some(audit_logger));
        let router = Arc::new(router);
        let hot_config = Arc::new(HotReloadConfig::new(
            config.clone(),
            "config/config.toml".to_string(),
        ));
        let config_service = Arc::new(ConfigManager::new(hot_config, router.clone()));
        let handlers = Arc::new(ApiHandlers::with_api_key_repository(
            router,
            config_service,
            Arc::new(MockApiKeyRepo),
        ));
        let auth = Arc::new(ApiKeyAuth::new(Arc::new(MockApiKeyRepo), true));
        let rate_limiter = Arc::new(RateLimiter::new(10000, 100));
        let audit_logger = Arc::new(AuditLogger::new(10000));

        let _router =
            nebulaid::server::router::create_router(handlers, auth, rate_limiter, audit_logger)
                .await;
    }

    #[tokio::test]
    async fn test_graceful_shutdown() {
        setup_test_env();
        use async_trait::async_trait;

        #[derive(Clone)]
        struct MockApiKeyRepo;

        #[async_trait]
        impl database::ApiKeyRepository for MockApiKeyRepo {
            async fn create_api_key(
                &self,
                _request: &database::CreateApiKeyRequest,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_secret".to_string(),
                    grace_expires_at: None,
                })
            }

            async fn get_api_key_by_id(
                &self,
                _key_id: &str,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn validate_api_key(
                &self,
                _key_id: &str,
                _key_secret: &str,
            ) -> nebulaid::core::types::Result<Option<database::AuthenticatedKey>> {
                Ok(None)
            }

            async fn list_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
                _limit: Option<u32>,
                _offset: Option<u32>,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }

            async fn delete_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn revoke_api_key(&self, _id: uuid::Uuid) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn update_last_used(
                &self,
                _key: uuid::Uuid,
            ) -> nebulaid::core::types::Result<()> {
                Ok(())
            }

            async fn get_admin_api_key(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            async fn count_api_keys(
                &self,
                _workspace_id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            /// admin 守卫用：本 mock 只做 bin 装配，与 get_api_key_by_id 一样返回 None。
            async fn find_api_key_by_row_id(
                &self,
                _id: uuid::Uuid,
            ) -> nebulaid::core::types::Result<Option<database::ApiKeyInfo>> {
                Ok(None)
            }

            /// admin 守卫用：本 mock 只做 bin 装配，与 count_api_keys 一样返回 0。
            async fn count_admin_keys(&self) -> nebulaid::core::types::Result<u64> {
                Ok(0)
            }

            async fn rotate_api_key(
                &self,
                _key_id: &str,
                _grace_period_seconds: u64,
            ) -> nebulaid::core::types::Result<database::ApiKeyWithSecret> {
                Ok(database::ApiKeyWithSecret {
                    key: database::ApiKeyResponse {
                        id: uuid::Uuid::new_v4(),
                        key_id: "mock_rotated_key_id".to_string(),
                        key_prefix: "nino_".to_string(),
                        name: "Mock Rotated Key".to_string(),
                        description: None,
                        role: database::ApiKeyRole::User,
                        rate_limit: 10000,
                        enabled: true,
                        expires_at: None,
                        created_at: chrono::Utc::now().naive_utc(),
                    },
                    key_secret: "mock_rotated_secret".to_string(),
                    grace_expires_at: None,
                })
            }

            async fn get_keys_older_than(
                &self,
                _age_threshold_days: i64,
            ) -> nebulaid::core::types::Result<Vec<database::ApiKeyInfo>> {
                Ok(vec![])
            }
        }

        let config = Config::default();
        let audit_logger: Arc<dyn nebulaid::core::algorithm::AuditLogger> =
            Arc::new(AuditLogger::new(10000));
        let router = AlgorithmRouter::new(config.clone(), Some(audit_logger));
        let router = Arc::new(router);
        let hot_config = Arc::new(HotReloadConfig::new(
            config.clone(),
            "config/config.toml".to_string(),
        ));
        let config_service = Arc::new(ConfigManager::new(hot_config, router.clone()));
        let handlers = Arc::new(ApiHandlers::with_api_key_repository(
            router,
            config_service.clone(),
            Arc::new(MockApiKeyRepo),
        ));
        let auth = Arc::new(ApiKeyAuth::new(Arc::new(MockApiKeyRepo), true));
        let rate_limiter = Arc::new(RateLimiter::new(10000, 100));
        let audit_logger = Arc::new(AuditLogger::new(10000));

        let server = tokio::spawn(async move {
            start_http_server(
                SocketAddr::from(([127, 0, 0, 1], 0)),
                handlers,
                auth,
                rate_limiter,
                audit_logger,
                config_service,
                None,
            )
            .await
        });

        tokio::time::sleep(std::time::Duration::from_millis(100)).await;

        let _ = tokio::time::timeout(std::time::Duration::from_secs(2), shutdown_signal()).await;

        server.abort();
    }

    // ==================== T008: 生产环境 TLS 强制校验 ====================

    #[test]
    fn test_validate_tls_production_tls_disabled_no_escape_hatch_errors() {
        // production + tls.enabled=false + 无逃生门 → 拒绝启动（Err → exit 非零）
        let result = validate_tls_required_in_production(Environment::Production, false, None);
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_tls_production_tls_disabled_escape_hatch_allows() {
        // NEBULA_ALLOW_INSECURE_TLS=1 → 显式放行（调用方负责 warn）
        let result = validate_tls_required_in_production(Environment::Production, false, Some("1"));
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_tls_production_tls_enabled_ok() {
        // TLS 已启用 → 直接通过，与逃生门无关
        let result = validate_tls_required_in_production(Environment::Production, true, None);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_tls_development_unaffected() {
        // 开发模式不强制 TLS
        let result = validate_tls_required_in_production(Environment::Development, false, None);
        assert!(result.is_ok());
    }

    #[test]
    fn test_validate_tls_escape_hatch_value_other_than_1_rejected() {
        // 逃生门仅认字面量 "1"，其余取值视为未启用
        let result =
            validate_tls_required_in_production(Environment::Production, false, Some("true"));
        assert!(result.is_err());
        let result = validate_tls_required_in_production(Environment::Production, false, Some(""));
        assert!(result.is_err());
    }

    // ==================== T016: 分布式锁装配 fail-closed ====================

    /// T016 —— 配置显式含 etcd endpoints + 不可达端点 → 装配必须失败（fail-closed）。
    ///
    /// `etcd_client::Client::connect` 是 lazy 的，`EtcdClientWrapper::new` 对不可达
    /// endpoint 也返回 Ok；`assemble_coordination` 因此在构造后 ping 探活，把
    /// "配置要求 etcd 但实际不可用" 确定性地转为 Err（main 据此打印本地化错误
    /// 并以非零码退出），不再静默回退 LocalDistributedLock。
    #[cfg(feature = "etcd")]
    #[tokio::test]
    async fn test_assemble_coordination_fail_closed_on_unreachable_etcd() {
        let mut config = Config::default();
        config.etcd.endpoints = vec!["http://127.0.0.1:1".to_string()];
        config.etcd.connect_timeout_ms = 300;

        let result = assemble_coordination(&config).await;
        let err_msg = match result {
            Err(e) => e.to_string(),
            Ok(_) => panic!("配置显式含 etcd endpoints 但端点不可达时必须拒绝装配（fail-closed）"),
        };
        assert!(
            err_msg.contains("127.0.0.1:1") || err_msg.contains("ping"),
            "错误信息应指向不可达端点或 ping 探活，实际: {err_msg}"
        );
    }

    /// T016 —— 未配置 endpoints → 单机本地锁放行（合法），共享 client 为 None。
    #[cfg(feature = "etcd")]
    #[tokio::test]
    async fn test_assemble_coordination_local_lock_when_no_endpoints() {
        let mut config = Config::default();
        config.etcd.endpoints = vec![];

        let components = assemble_coordination(&config)
            .await
            .expect("未配置 etcd 时装配必须放行（单机合法）");
        assert!(
            components.client.is_none(),
            "未配置 etcd 时不应产出共享 client"
        );
        assert!(components.lock.is_healthy(), "LocalDistributedLock 应恒健康");

        // 本地锁应可正常 acquire/release（号段分配互斥在单机内仍生效）
        let guard = components
            .lock
            .acquire("t016-local-key", 5)
            .await
            .expect("本地锁 acquire 必须成功");
        guard.release().await.expect("本地锁 release 必须成功");
    }

    /// T016 verify 钉（bin 侧可达性）—— `DbSegmentLoader` 经 mod.rs re-export
    /// 后可从 bin crate 构造（`SegmentAlgorithm::new(dc).with_segment_loader(...)`
    /// 装配契约的 bin 侧入口）。注意：服务端 Segment 实例由
    /// `AlgorithmRouter::initialize` 经 `SegmentFactory` 内部构建，bin 侧
    /// 注入缝（router/traits 增设）不在本 lane 文件所有权内。
    #[test]
    fn test_db_segment_loader_assembly_api_reachable_from_bin() {
        use dbnexus::sea_orm::{DatabaseBackend, MockDatabase};

        let db = MockDatabase::new(DatabaseBackend::Postgres).into_connection();
        let repo = Arc::new(database::SeaOrmRepository::new(db, "test_salt".to_string()));
        // 构造成功即证明 re-export 与泛型约束（SeaOrmRepository: SegmentRepository）
        // 在 bin 侧可用；字段与步长断言归 lib 侧单测（segment.rs）所有。
        let _loader = nebulaid::core::algorithm::DbSegmentLoader::new(repo);
    }

    // ==================== T018: 无 etcd 默认 worker 标识告警 ====================

    /// T018 —— 未配置 etcd + worker_id/dc_id 默认 0 → 必须告警。
    #[test]
    fn test_warn_default_worker_identity_triggers_on_defaults() {
        assert!(should_warn_default_worker_identity(false, 0, 0));
        assert!(should_warn_default_worker_identity(false, 0, 3));
        assert!(should_warn_default_worker_identity(false, 5, 0));
    }

    /// T018 —— 已配置 etcd（有运行时分配兜底）→ 不告警，即使值为默认 0。
    #[test]
    fn test_warn_default_worker_identity_skipped_when_etcd_configured() {
        assert!(!should_warn_default_worker_identity(true, 0, 0));
        assert!(!should_warn_default_worker_identity(true, 0, 3));
    }

    /// T018 —— 未配置 etcd 但标识均已显式配置（非 0）→ 不告警。
    #[test]
    fn test_warn_default_worker_identity_skipped_when_explicitly_configured() {
        assert!(!should_warn_default_worker_identity(false, 1, 1));
        assert!(!should_warn_default_worker_identity(false, 255, 31));
    }
}
